/* ======================================================================
   QUMC Review & Development Center — Performance + GRC
   Build: 2026-08-20 v223 split approval queues + lightweight manager decisions
   Request types:
   1) Existing Item Review & Update
   2) New Item Request
   ====================================================================== */
(function(){
  'use strict';

  var records=[],currentPlatform='grc',currentRootId='advRootGrc',currentView='requests';
  var dashboardFilter='all',departmentFilter='',dashboardSearch='',dashboardStatus='';
  var adminSearch='',adminStatus='',adminDepartment='',loading=false,lastLoadError='',selectedRequest=null,selectedRating=0,liveUnsub=null,livePayload=null,managerRiskRecords=[];

  var STATUS_LABELS={open:'Open',in_progress:'In Progress',closed:'Closed'};
  function statusKey(value){
    value=String(value||'open').toLowerCase();
    if(['closed','completed','cancelled','duplicate','out_of_scope','knowledge_guide'].indexOf(value)>=0)return'closed';
    if(['in_progress','awaiting_requester_information','responded'].indexOf(value)>=0)return'in_progress';
    return'open';
  }
  var TYPE_LABELS={edit_review:'Existing Item Review & Update',new:'New Item Request',clarification:'Existing Item Review & Update',review:'Existing Item Review & Update'};
  var PLATFORM_LABELS={performance:'Performance',grc:'GRC'};
  var ITEM_TYPES={
    performance:[
      {value:'kpi_definition',label:'KPI Definition / Indicator',key:'kpis'},
      {value:'benchmark',label:'Benchmark',key:'kpis'},
      {value:'target',label:'Target',key:'kpis'},
      {value:'formula',label:'Calculation Formula',key:'kpis'},
      {value:'data_source',label:'Data Source',key:'kpis'},
      {value:'quarterly_result',label:'Quarterly Result',key:'kpis'},
      {value:'gap_analysis',label:'Gap Analysis',key:'kpis'},
      {value:'corrective_action',label:'Corrective Action',key:'kpis'},
      {value:'ownership',label:'KPI Ownership / Responsibility',key:'kpis'},
      {value:'dashboard_view',label:'Dashboard / Visualization',key:'kpis'}
    ],
    grc:[
      {value:'policy',label:'Policy / Procedure',key:'policies'},
      {value:'form',label:'Form',key:'forms'},
      {value:'plan',label:'Plan',key:'plans'},
      {value:'operational_plan',label:'Operational Plan',key:'operationalPlans'},
      {value:'code',label:'Emergency Code Record',key:'codes'},
      {value:'action',label:'Action Plan',key:'actions'},
      {value:'initiative',label:'Initiative',key:'initiatives'},
      {value:'manual',label:'Manual / Guideline',key:'manuals'},
      {value:'report',label:'Report',key:'reports'},
      {value:'cbahi',label:'CBAHI Requirement',key:'cbahi'},
      {value:'jci',label:'JCI Requirement',key:'jci'}
    ]
  };
  var DEPARTMENTS={
    safety:{name:'Safety',code:'SAF'},maintenance:{name:'Maintenance',code:'MNT'},housekeeping:{name:'Housekeeping',code:'HSK'},
    laundry:{name:'Laundry',code:'LND'},projects:{name:'Project Management',code:'PRJ'},governance:{name:'Governance & Performance',code:'GOV'},division:{name:'Governance & Performance',code:'GOV'}
  };

  function esc(v){return String(v==null?'':v).replace(/[&<>'"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c];});}
  function role(){if(typeof window._normalizePortalRole==='function')return window._normalizePortalRole(window._fbRole||window.currentUserRole||'viewer');return String(window._fbRole||window.currentUserRole||'viewer').trim().toLowerCase().replace(/[\s-]+/g,'_').replace(/^superadmin$/,'super_admin');}
  function isAdmin(){return role()==='admin'||role()==='super_admin';}
  function isGovernancePerformanceManager(){return role()==='governance_performance_manager';}
  function hasAllDashboardScope(){return isAdmin()||isGovernancePerformanceManager();}
  function canViewDashboard(){var r=role(),p=Array.isArray(window._fbPerms)?window._fbPerms:[];return isAdmin()||r==='governance_performance_manager'||p.indexOf('view_request_analytics')>=0||p.indexOf('*')>=0;}
  function isSuperAdmin(){return role()==='super_admin';}
  function isDepartmentManager(){var r=role();if(r==='department_manager')return true;var raw=String(window._fbRole||window.currentUserRole||'').trim().toLowerCase().replace(/[\s-]+/g,'_');if(raw==='department_manager'||raw==='dept_manager')return true;return !!window.__grcManagerDepartmentKey&&raw!=='governance_performance_manager';}
  function userEmail(){return String(window._fbUser||window.currentUserEmail||'').toLowerCase().trim();}
  function rawUserDepartment(){return Object.prototype.hasOwnProperty.call(window,'_fbDept')?window._fbDept:window.currentUserDept;}
  function userDepartmentKey(){
    /* Department Manager queues are fetched with a server-fresh Firestore
       profile. Use that exact canonical department for every post-fetch filter
       too; falling back to a stale _fbDept here used to fetch the right rows and
       then immediately hide them from the manager UI. */
    if(isDepartmentManager()&&window.__grcManagerDepartmentKey)return String(window.__grcManagerDepartmentKey||'');
    var raw=String(rawUserDepartment()==null?'':rawUserDepartment()).trim();
    if(!raw||/^(null|none|undefined|n\/?a|na|unassigned|not assigned|-|—)$/i.test(raw))return'';
    var low=raw.toLowerCase(),compact=low.replace(/[^a-z0-9\u0600-\u06ff]+/g,' '),tokens=compact.split(/\s+/).filter(Boolean),has=function(x){return tokens.indexOf(x)>=0;};
    if(low.indexOf('السلامة')>=0||low.indexOf('سلامة')>=0||low.indexOf('safety')>=0||has('saf'))return'safety';
    if(low.indexOf('الصيانة')>=0||low.indexOf('صيانة')>=0||low.indexOf('maintenance')>=0||has('mnt'))return'maintenance';
    if(low.indexOf('المغسلة')>=0||low.indexOf('مغسلة')>=0||low.indexOf('الغسيل')>=0||low.indexOf('laundry')>=0||has('lnd')||has('lund'))return'laundry';
    if(low.indexOf('النظافة')>=0||low.indexOf('نظافة')>=0||low.indexOf('housekeeping')>=0||low.indexOf('cleaning')>=0||has('hsk')||has('hk'))return'housekeeping';
    if(low.indexOf('المشاريع')>=0||low.indexOf('مشاريع')>=0||low.indexOf('project')>=0||has('prj')||has('pmd')||low==='pm')return'projects';
    if(low.indexOf('الحوكمة')>=0||low.indexOf('حوكمة')>=0||low.indexOf('الأداء')>=0||low.indexOf('الاداء')>=0||low.indexOf('governance')>=0||low.indexOf('performance')>=0||has('gov'))return'governance';
    if(low.indexOf('facility management')>=0||low.indexOf('facilities management')>=0||low.indexOf('المرافق')>=0||low.indexOf('division')>=0||low==='fms')return'division';
    var normalized=low.replace(/[\s&/-]+/g,'_');return DEPARTMENTS[normalized]?normalized:'';
  }
  function workflowStage(r){var x=String(r&&r.workflowStage||r&&r.status||'').trim().toLowerCase();return x==='submitted'?'pending_super_admin':x;}
  function workflowLabel(r){var x=workflowStage(r),m={pending_department_manager:'Pending Department Manager Approval',pending_super_admin:'Pending Super Admin Review',returned_requester:'Returned for Update',rejected_manager:'Rejected by Department Manager',responded:'Super Admin Response Sent',awaiting_requester_information:'Awaiting Requester Information',clarification_received:'Clarification Received',requester_confirmed:'Requester Confirmed',closed:'Closed'};return m[x]||String(x||'Open').replace(/_/g,' ').replace(/\b\w/g,function(c){return c.toUpperCase();});}
  function isManagerApprovalRecord(r){if(!isDepartmentManager()||!r)return false;var stage=workflowStage(r);if(stage!=='pending_department_manager')return false;if(String(r&&r.userEmail||'').toLowerCase().trim()===userEmail())return false;var assigned=r._managerAssigned===true||String(r.assignedManagerEmail||'').toLowerCase().trim()===userEmail();var dept=String(r.departmentKey||'').trim();var mine=String(userDepartmentKey()||'').trim();return assigned||(!assigned&&!!mine&&dept===mine);}
  function isManagerOwnRequest(r){return isDepartmentManager()&&String(r&&r.userEmail||'').toLowerCase().trim()===userEmail();}
  function isOwnRequest(r){return String(r&&r.userEmail||'').toLowerCase().trim()===userEmail();}
  function departmentName(k){return(DEPARTMENTS[k]&&DEPARTMENTS[k].name)||String(k||'—');}
  function departmentCode(k){return(DEPARTMENTS[k]&&DEPARTMENTS[k].code)||'FMS';}
  function root(){return document.getElementById(currentRootId);}
  function host(){var r=root();return r&&r.querySelector('#advViewHost');}
  function recordPlatform(r){return String(r&&r.platform||'grc').toLowerCase()==='performance'?'performance':'grc';}
  function normalizedType(r){var t=String(r&&r.requestType||'');return t==='new'?'new':'edit_review';}
  function typeLabel(r){return TYPE_LABELS[String(r&&r.requestType||'')]||TYPE_LABELS[normalizedType(r)];}
  function isRelevantRecord(r){return r&&recordPlatform(r)===currentPlatform&&String(r.serviceType||'review_guidance')!=='session';}
  function formatDate(v,withTime){if(!v)return'—';var d=v&&v.toDate?v.toDate():new Date(v);if(isNaN(d.getTime()))return'—';try{return new Intl.DateTimeFormat('en-GB',withTime?{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}:{day:'2-digit',month:'short',year:'numeric'}).format(d);}catch(_){return d.toLocaleString();}}
  function timeMs(v){if(!v)return 0;var d=v&&v.toDate?v.toDate():new Date(v);return isNaN(d.getTime())?0:d.getTime();}
  function responseMinutes(r){var a=timeMs(r.createdAt),b=timeMs(r.firstRespondedAt||r.respondedAt);if(a&&b&&b>=a)return Math.max(1,Math.ceil((b-a)/60000));var stored=Number(r.responseMinutes);return Number.isFinite(stored)&&stored>0?stored:null;}
  function durationText(m){if(m==null)return'Not Responded';if(m<60)return m+' min';var h=Math.floor(m/60),x=m%60;if(h<24)return h+' hr'+(h===1?'':'s')+(x?' '+x+' min':'');var d=Math.floor(h/24),rh=h%24;return d+' day'+(d===1?'':'s')+(rh?' '+rh+' hrs':'');}
  function statusLabel(s){var key=statusKey(s);return STATUS_LABELS[key]||'Open';}
  function statusBadge(s){var key=statusKey(s);return'<span class="adv-status '+esc(key)+'">'+esc(STATUS_LABELS[key])+'</span>';}
  function stars(v){var n=Number(v||0);return n?'<span title="'+n+' out of 5">'+('★'.repeat(n))+('☆'.repeat(Math.max(0,5-n)))+'</span>':'—';}
  function toast(message){var r=root()||document.body,old=r.querySelector&&r.querySelector('.adv-toast');if(old)old.remove();var e=document.createElement('div');e.className='adv-toast';e.textContent=message;r.appendChild(e);setTimeout(function(){e.remove();},4200);}
  function clearFieldErrors(){
    document.querySelectorAll('#advModal .adv-field-invalid').forEach(function(el){el.classList.remove('adv-field-invalid');});
    document.querySelectorAll('#advModal [aria-invalid="true"]').forEach(function(el){el.removeAttribute('aria-invalid');});
  }
  function clearSubmitError(){var box=document.getElementById('advSubmitError');if(box){box.style.display='none';box.textContent='';}clearFieldErrors();}
  function markFieldInvalid(target){
    if(!target)return;
    var el=typeof target==='string'?document.getElementById(target):target;if(!el)return;
    try{el.setAttribute('aria-invalid','true');}catch(_){}
    var wrap=el.closest&&el.closest('.adv-field,.adv-form-dependency');
    if(!wrap&&el.id==='advRelatedField')wrap=el;
    if(wrap)wrap.classList.add('adv-field-invalid');
  }
  function showSubmitError(message,target){message=String(message||'Request submission failed.');if(target)markFieldInvalid(target);var box=document.getElementById('advSubmitError');if(box){box.innerHTML='<strong>Request not submitted</strong><span>'+esc(message)+'</span>';box.style.display='flex';try{box.scrollIntoView({behavior:'smooth',block:'nearest'});}catch(_){}}toast(message);}
  function friendlySubmitError(error){
    var raw=String(error&&error.code||error&&error.message||error||'').trim(),text=raw.toLowerCase();
    if(!navigator.onLine)return'No internet connection. Reconnect, then submit the request again.';
    if(/submission-timeout|deadline-exceeded|timed out|timeout/.test(text))return'The request service did not respond in time. Check My Requests first; if the request is not listed, check the connection and submit it again.';
    if(/rules-version-mismatch/.test(text))return raw.replace(/^rules-version-mismatch:/,'');
    if(/profile-department-unrecognized/.test(text)){var dept=raw.split(':').slice(1).join(':')||'Unknown';return'Your account department is not recognized by the Review & Development workflow ('+dept+'). Update the user department to a supported department, then sign in again.';}
    if(/permission-denied|missing or insufficient permissions/.test(text)){var diag=raw.indexOf(':')>=0?raw.split(':').slice(1).join(':').trim():'';var verified=(window.__advRulesV39Verified===true||window.__grcRulesV39Verified===true);return(verified?'Firestore Rules v39 passed the version probe, but Firebase rejected this request.':'Firebase rejected this request because the deployed Firestore Rules do not allow it.')+(diag?' Diagnostic: '+diag:'');}
    if(/unauthenticated|not authenticated/.test(text))return'Your session is no longer active. Sign in again, then resubmit the request.';
    if(/unavailable|network-request-failed|failed to fetch|offline/.test(text))return'The request service is temporarily unavailable. Check the connection and try again.';
    if(/resource-exhausted|quota/.test(text))return'The request could not be saved because the database service limit was reached. Contact the system administrator.';
    return raw||'The request could not be submitted. Review the entered data and try again.';
  }
  function submitWithTimeout(promise,ms){return Promise.race([promise,new Promise(function(_,reject){setTimeout(function(){reject(new Error('submission-timeout'));},ms||20000);})]);}
  function showSubmitSuccess(code,warning,workflowStage,departmentKey){var old=document.getElementById('advSubmitSuccess');if(old)old.remove();var stage=String(workflowStage||''),dept=departmentName(departmentKey||userDepartmentKey()),routeHtml='';if(stage==='pending_department_manager'){routeHtml='<p>Your request has been sent to the <strong>'+esc(dept)+' Department Manager</strong> for approval.</p><div class="adv-success-route"><strong>Approval Route</strong><span>Department Manager → Super Admin</span><small>Once the Department Manager approves the request, it will be forwarded automatically to Super Admin for final review. If the Department Manager rejects it, the request will be closed and will not be forwarded.</small></div>';}else{routeHtml='<p>Your request has been sent directly to <strong>Super Admin</strong> for review.</p><div class="adv-success-route"><strong>Approval Route</strong><span>Super Admin</span><small>No Department Manager approval is required for this request.</small></div>';}var ov=document.createElement('div');ov.id='advSubmitSuccess';ov.className='adv-success-backdrop';ov.innerHTML='<div class="adv-success-card" role="dialog" aria-modal="true" aria-labelledby="advSuccessTitle"><div class="adv-success-icon">✓</div><h2 id="advSuccessTitle">Request Submitted Successfully</h2>'+routeHtml+(code?'<div class="adv-success-code"><span>Request Code</span><strong>'+esc(code)+'</strong></div>':'')+(warning?'<div class="adv-success-warning">'+esc(warning)+'</div>':'')+'<button type="button" class="adv-btn primary adv-success-ok" onclick="window._advCloseSubmitSuccess()">OK</button></div>';document.body.appendChild(ov);ov.addEventListener('click',function(e){if(e.target===ov)window._advCloseSubmitSuccess();});setTimeout(function(){var b=ov.querySelector('button');if(b)b.focus();},20);}
  window._advCloseSubmitSuccess=function(){var x=document.getElementById('advSubmitSuccess');if(x)x.remove();};
  function apiReady(n){return typeof window[n]==='function';}
  function audit(a,d){try{if(typeof window.addAudit==='function')window.addAudit(a,d);else if(typeof window._recordAuditDirect==='function')window._recordAuditDirect(a,d);}catch(_){}}
  function approved(r){return statusKey(r&&r.status)==='closed';}
  function isOpen(r){return statusKey(r&&r.status)!=='closed';}
  function canRateReview(r){return statusKey(r&&r.status)==='closed'&&String(r&&r.status||'').toLowerCase()!=='cancelled';}

  function moduleCard(id,icon,title,desc,sa){return'<button type="button" class="adv-module-card '+(currentView===id?'is-active':'')+'" data-adv-view="'+id+'" onclick="window._advSwitchView(\''+id+'\')">'+(sa?'<span class="adv-sa-pill">SUPER ADMIN</span>':'')+'<span class="adv-module-icon">'+icon+'</span><h3>'+title+'</h3><p>'+desc+'</p></button>';}
  function pageSkeleton(platform,rootId){
    currentPlatform=platform;currentRootId=rootId;var label=PLATFORM_LABELS[platform];
    return'<div class="adv-platform-root" id="'+rootId+'" data-adv-platform="'+platform+'"><div class="adv-shell">'+
      '<div class="grc-hero adv-hero"><div class="grc-hero-row"><div><div class="grc-eyebrow">'+label+' · INTERNAL REVIEW & DEVELOPMENT SERVICE</div><h1>Review & Development Center</h1><p>Request an update and professional review for an existing record, or submit a request for a new record. Available items are limited to this platform and the requester\'s department.</p></div></div></div>'+
      '<div class="adv-privacy-note"><span class="adv-privacy-icon">i</span><div><strong>Before submitting a request</strong>Choose Existing Item Review & Update for an item already listed, or New Item Request for an item that does not yet exist. Request details are available to authorized Governance & Performance analytics roles; approval actions remain limited to the assigned Department Manager and Super Admin.</div></div>'+
      '<div class="adv-module-grid '+(canViewDashboard()?'adv-module-grid-admin':'adv-module-grid-user')+'">'+(canViewDashboard()?moduleCard('dashboard','▦','Review & Development Dashboard',hasAllDashboardScope()?'Approval indicators and a non-personal request register across all FMS departments.':'Approval indicators and a non-personal request register scoped to this platform and department.'):'')+moduleCard('requests','✦','Review & Development Requests',isAdmin()?'Review requests, request information, respond and close completed cases.':'Submit and follow Existing Item Review & Update or New Item Request cases.')+'</div>'+
      '<div id="advViewHost"><div class="adv-loading">Loading Review & Development Center…</div></div></div></div>';
  }
  window._grcAdvisoryPage=function(){return pageSkeleton('grc','advRootGrc');};
  window._grcAdvisoryMount=function(){mount('grc','advRootGrc');};
  window._performanceAdvisoryMount=function(){var h=document.getElementById('performanceAdvisoryRoot');if(!h)return;if(!h.querySelector('#advRootPerformance'))h.innerHTML=pageSkeleton('performance','advRootPerformance');mount('performance','advRootPerformance');};
  function applyLivePayload(payload){if(!payload||!root())return;livePayload=payload;if(isDepartmentManager()&&Array.isArray(payload.managerRiskRecords))managerRiskRecords=payload.managerRiskRecords;var next=currentView==='dashboard'?payload.publicRecords:payload.records;if(!Array.isArray(next))return;var incoming=next.filter(isRelevantRecord),errs=payload.errors||{},keys=currentView==='dashboard'?['primary']:((isDepartmentManager()?['manager']:['primary'])),messages=keys.filter(function(k){return !!errs[k];}).map(function(k){return k+': '+String(errs[k]);});if(errs.fallback)console.warn('[Review Development] legacy fallback sync skipped',errs.fallback);if(messages.length)console.warn('[Review Development] live sync warning',messages.join(' · '));/* Keep the last verified rows on a transient listener denial instead of replacing the page with an empty/error state. */if(!messages.length||incoming.length||!records.length)records=incoming;lastLoadError=messages.join(' · ');loading=false;if(!managerInlineDecisionActive())renderView();if(isDepartmentManager()&&typeof window._grcRiskInjectManagerQueue==='function')window._grcRiskInjectManagerQueue(managerRiskRecords,records.filter(isManagerApprovalRecord));if(currentView==='requests'&&!isAdmin())showRatingNotification();}
  function mount(platform,rootId){if(liveUnsub){try{liveUnsub();}catch(_){}liveUnsub=null;}livePayload=null;currentPlatform=platform;currentRootId=rootId;/* Action queues are the operational landing view for Admin/Super Admin. The analytics dashboard remains available as a separate card. */currentView='requests';dashboardFilter='all';departmentFilter='';loading=true;lastLoadError='';renderView();if(apiReady('_advisorySubscribe')){liveUnsub=window._advisorySubscribe(applyLivePayload);}else{loading=false;loadRecords(false);if(isDepartmentManager()){var managerTimer=setInterval(function(){if(root()&&currentView==='requests')loadRecords(true);},5000);liveUnsub=function(){clearInterval(managerTimer);};}}}
  window._advSwitchView=function(view){if(view==='management')view='requests';if(view==='dashboard'&&!canViewDashboard())view='requests';currentView=view;dashboardSearch='';dashboardStatus='';adminSearch='';adminStatus='';adminDepartment='';var r=root();if(r)r.querySelectorAll('.adv-module-card').forEach(function(x){x.classList.toggle('is-active',x.getAttribute('data-adv-view')===view);});if(livePayload)applyLivePayload(livePayload);else loadRecords();};

  function managerInlineDecisionActive(){return !!document.querySelector('#advViewHost .adv-manager-inline-decision:not([hidden])');}
  async function loadRecords(silent){if(loading)return;var quiet=!!silent;loading=true;lastLoadError='';if(!quiet)renderView();try{var next;if(currentView==='dashboard'){if(!apiReady('_advisoryGetPublic'))throw new Error('Record request data service is unavailable.');next=await window._advisoryGetPublic();managerRiskRecords=[];}else if(isAdmin()){if(!apiReady('_advisoryGetAll'))throw new Error('Record request data service is unavailable.');next=await window._advisoryGetAll();managerRiskRecords=[];}else if(isDepartmentManager()){if(!apiReady('_advisoryGetManagerQueue'))throw new Error('Department approval services are unavailable.');var managerQueue=await window._advisoryGetManagerQueue();next=Array.isArray(managerQueue)?managerQueue:[];managerRiskRecords=Array.isArray(managerQueue&&managerQueue._grcRiskRecords)?managerQueue._grcRiskRecords:[];if(!Array.isArray(managerQueue)&&managerQueue&&Array.isArray(managerQueue.review)){next=managerQueue.review;}if(!Array.isArray(managerRiskRecords)&&managerQueue&&Array.isArray(managerQueue.risk))managerRiskRecords=managerQueue.risk;lastLoadError='';}else{if(!apiReady('_advisoryGetMine'))throw new Error('Record request data service is unavailable.');next=await window._advisoryGetMine();managerRiskRecords=[];}records=(next||[]).filter(isRelevantRecord);if(isDepartmentManager()&&typeof window._grcRiskInjectManagerQueue==='function')window._grcRiskInjectManagerQueue(managerRiskRecords,records.filter(isManagerApprovalRecord));}catch(e){console.warn('[Review Development] refresh failed',e&&e.message||e);lastLoadError=[lastLoadError,String(e&&e.message||e||'Unable to load requests.')].filter(Boolean).join(' · ');}loading=false;if(!quiet||!managerInlineDecisionActive())renderView();if(currentView==='requests'&&!isAdmin())showRatingNotification();}
  function refreshAfterMutation(){return isDepartmentManager()?loadRecords(false):(liveUnsub?Promise.resolve():loadRecords(false));}
  window._advRefreshAfterManagerQueue=function(detail){if(!isDepartmentManager())return;detail=detail&&detail.detail?detail.detail:detail||{};if(Array.isArray(detail.review))records=detail.review.filter(isRelevantRecord);if(Array.isArray(detail.risk))managerRiskRecords=detail.risk;renderView();};
  window._advReload=function(){loadRecords(false);};
  function renderView(){var h=host();if(!h)return;if(loading){h.innerHTML='<div class="adv-loading">Loading Review & Development Center…</div>';return;}if(currentView==='dashboard'&&!canViewDashboard())currentView='requests';if(currentView==='management')currentView='requests';h.innerHTML=(currentView==='dashboard'?dashboardHtml():requestsHtml());}

  function scopedPublicRecords(){var all=records.filter(isRelevantRecord);return hasAllDashboardScope()?all:all.filter(function(r){return r.departmentKey===userDepartmentKey();});}
  function filterRecords(base){var q=dashboardSearch.toLowerCase().trim();return base.filter(function(r){if(departmentFilter&&r.departmentKey!==departmentFilter)return false;if(dashboardStatus&&statusKey(r.status)!==dashboardStatus)return false;var t=normalizedType(r);if(dashboardFilter==='edit_review'&&t!=='edit_review')return false;if(dashboardFilter==='new'&&t!=='new')return false;if(dashboardFilter==='approved'&&!approved(r))return false;if(dashboardFilter==='open'&&statusKey(r.status)!=='open')return false;if(dashboardFilter==='in_progress'&&statusKey(r.status)!=='in_progress')return false;if(q&&[r.code,typeLabel(r),r.category,relatedText(r),departmentName(r.departmentKey),statusLabel(r.status)].join(' ').toLowerCase().indexOf(q)<0)return false;return true;});}
  function metric(label,value,sub,filter,tone){var icons={info:'▦',good:'✓',warn:'△',purple:'◇',bad:'!'};return'<div class="grc-metric-card adv-metric-card '+tone+' clickable '+(dashboardFilter===filter?'is-active':'')+'" onclick="window._advDashboardFilter(\''+filter+'\')" tabindex="0" role="button"><div class="grc-metric-top"><span class="grc-metric-icon">'+(icons[tone]||'▦')+'</span></div><div class="grc-metric-value">'+value+'</div><div class="grc-metric-label">'+label+'</div><div class="grc-metric-foot"><span class="grc-metric-sub">'+sub+'</span><span class="grc-metric-arrow">›</span></div></div>';}
  function dashboardMetric(label,value,sub,tone){return'<div class="grc-metric-card adv-metric-card '+tone+'"><div class="grc-metric-top"><span class="grc-metric-icon">'+(tone==='good'?'✓':tone==='warn'?'△':'▦')+'</span></div><div class="grc-metric-value">'+value+'</div><div class="grc-metric-label">'+label+'</div><div class="grc-metric-foot"><span class="grc-metric-sub">'+sub+'</span></div></div>';}
  function requestTypeDashboard(title,type,base){
    var rows=base.filter(function(r){return normalizedType(r)===type;}),open=rows.filter(function(r){return statusKey(r.status)==='open';}).length,progress=rows.filter(function(r){return statusKey(r.status)==='in_progress';}).length,closed=rows.filter(function(r){return statusKey(r.status)==='closed';}).length,rate=rows.length?Math.round(closed/rows.length*100):0;
    return'<div class="adv-type-dashboard"><div class="adv-type-dashboard-head"><div><h3>'+title+'</h3><p>'+PLATFORM_LABELS[currentPlatform]+' · Request workflow summary</p></div><span>'+rows.length+' requests</span></div><div class="adv-type-dashboard-metrics">'+dashboardMetric('Total',rows.length,'All requests in this category','info')+dashboardMetric('Open',open,'Newly submitted requests','bad')+dashboardMetric('In Progress',progress,'Being handled or awaiting information','warn')+dashboardMetric('Closed',closed,'Closed or cancelled requests','good')+dashboardMetric('Closure Rate',rate+'%',closed+' closed of '+rows.length+' requests','good')+'</div></div>';
  }
  function dashboardHtml(){
    var base=scopedPublicRecords(),editCount=base.filter(function(r){return normalizedType(r)==='edit_review';}).length,newCount=base.filter(function(r){return normalizedType(r)==='new';}).length,openCount=base.filter(function(r){return statusKey(r.status)==='open';}).length,progressCount=base.filter(function(r){return statusKey(r.status)==='in_progress';}).length,approvedCount=base.filter(approved).length,rate=base.length?Math.round(approvedCount/base.length*100):0,displayed=filterRecords(base);
    return'<section class="adv-view is-active"><div class="grc-section-head"><div><div class="grc-section-title">Review & Development Dashboard</div><div class="grc-section-sub">'+(hasAllDashboardScope()?'All FMS departments · '+PLATFORM_LABELS[currentPlatform]:'Department scope: '+esc(departmentName(userDepartmentKey()))+' · '+PLATFORM_LABELS[currentPlatform])+'</div></div><span class="grc-section-badge">No personal data</span></div><div class="adv-metric-grid">'+
      metric('Total Requests',base.length,'All submitted requests','all','info')+metric('New Item Requests',newCount,base.length?Math.round(newCount/base.length*100)+'% of total':'0% of total','new','info')+metric('Existing Item Review & Update',editCount,base.length?Math.round(editCount/base.length*100)+'% of total':'0% of total','edit_review','purple')+metric('Open Requests',openCount,'Open requests','open','bad')+metric('In Progress Requests',progressCount,'Requests currently being handled','in_progress','warn')+metric('Closed Requests',approvedCount,'Closed or cancelled requests','approved','good')+metric('Closure Rate',rate+'%',approvedCount+' closed of '+base.length+' requests','approved','good')+
      '</div>'+requestTypeDashboard('New Item Requests Dashboard','new',base)+requestTypeDashboard('Existing Item Review & Update Dashboard','edit_review',base)+registerHtml(displayed,base.length)+'</section>';
  }
  function filterTitle(){return{all:'All Requests',open:'Open Requests',in_progress:'In Progress',edit_review:'Existing Item Review & Update',new:'New Item Requests',approved:'Closed Requests'}[dashboardFilter]||'All Requests';}
  function registerHtml(list,total){var dept=hasAllDashboardScope()?'<select onchange="window._advDepartmentFilter(this.value,true)"><option value="">All Departments</option>'+Object.keys(DEPARTMENTS).filter(function(k){return k!=='division';}).map(function(k){return'<option value="'+k+'" '+(departmentFilter===k?'selected':'')+'>'+DEPARTMENTS[k].name+'</option>';}).join('')+'</select>':'';return'<div class="adv-card" style="margin-top:14px"><div class="adv-register-toolbar"><div><h3>Request & Review Register</h3><p>Each row contains non-personal request data only.</p></div><div class="adv-filter-note">Showing <b>'+list.length+'</b> of <b>'+total+'</b> requests · '+esc(filterTitle())+'</div></div><div class="adv-filters"><input value="'+esc(dashboardSearch)+'" placeholder="Search by code, item type or related record" oninput="window._advSetDashboardFilter(\'search\',this.value)">'+dept+'<select onchange="window._advSetDashboardFilter(\'status\',this.value)"><option value="">All Statuses</option>'+Object.keys(STATUS_LABELS).map(function(k){return'<option value="'+k+'" '+(dashboardStatus===k?'selected':'')+'>'+STATUS_LABELS[k]+'</option>';}).join('')+'</select><button class="adv-btn ghost" onclick="window._advResetFilters()">Reset</button></div>'+publicTable(list)+'</div>';}
  function relatedText(r){var a=Array.isArray(r.relatedItems)?r.relatedItems:[],v=a.map(function(x){return x.code?x.code+' — '+x.name:(x.name||x.label||'');}).filter(Boolean);if(r.relatedNewText)v.push('New: '+r.relatedNewText);return v.join('; ')||'—';}
  function publicTable(list){return'<div class="adv-table-wrap"><table class="adv-table"><thead><tr><th>Request Code</th><th>Request Type</th><th>Item Type</th><th>Related Record(s)</th><th>Department</th><th>Priority</th><th>Request Date</th><th>Status</th><th>First Response</th><th>Response Duration</th><th>Rating</th></tr></thead><tbody>'+(list.length?list.map(function(r){return'<tr><td class="adv-code">'+esc(r.code||r.id)+'</td><td>'+esc(typeLabel(r))+'</td><td>'+esc(r.category||r.relatedType||'—')+'</td><td>'+esc(relatedText(r))+'</td><td>'+esc(departmentName(r.departmentKey))+'</td><td>'+esc(r.priority||'Medium')+'</td><td>'+formatDate(r.createdAt,false)+'</td><td>'+statusBadge(r.status)+'</td><td>'+formatDate(r.firstRespondedAt||r.respondedAt,true)+'</td><td>'+durationText(responseMinutes(r))+'</td><td>'+stars(r.rating)+'</td></tr>';}).join(''):'<tr><td colspan="11"><div class="adv-empty">No requests match the selected filters.</div></td></tr>')+'</tbody></table></div>';}
  window._advDashboardFilter=function(f){dashboardFilter=f;renderView();setTimeout(function(){var r=root(),t=r&&r.querySelector('.adv-table-wrap');if(t)t.scrollIntoView({behavior:'smooth',block:'start'});},30);};
  window._advDepartmentFilter=function(k,fromSelect){departmentFilter=fromSelect?k:(departmentFilter===k?'':k);renderView();};
  window._advSetDashboardFilter=function(k,v){if(k==='search')dashboardSearch=String(v||'');if(k==='status')dashboardStatus=String(v||'');renderView();};
  window._advResetFilters=function(){dashboardFilter='all';departmentFilter='';dashboardSearch='';dashboardStatus='';renderView();};

  function requestsHtml(){return'<section class="adv-view is-active"><div class="grc-section-head"><div><div class="grc-section-title">Review & Development Requests</div><div class="grc-section-sub">'+(isAdmin()?'Review and respond to '+PLATFORM_LABELS[currentPlatform]+' requests.':isDepartmentManager()?'Approve GRC requests from your department, then follow your own submitted requests below.':'Submit an Existing Item Review & Update request or a New Item Request.')+'</div></div><button class="grc-primary-btn" onclick="window._advOpenGuidanceRequest()">＋ Submit Request</button></div>'+(isAdmin()?adminRequestsHtml():isDepartmentManager()?managerRequestsHtml():ownRequestsHtml())+'</section>';}
  function ownRequestsHtml(){var list=records.filter(function(r){if(isDepartmentManager())return isManagerOwnRequest(r);return String(r&&r.userEmail||'').toLowerCase().trim()===userEmail();}).slice().sort(function(a,b){return timeMs(b.createdAt)-timeMs(a.createdAt);});return'<div class="adv-card"><div class="adv-register-toolbar"><div><h3>Submitted Review & Development Requests</h3><p>Your '+PLATFORM_LABELS[currentPlatform]+' requests only.</p></div><button class="adv-btn ghost" onclick="window._advReload()">Refresh</button></div><div class="adv-table-wrap"><table class="adv-table" style="min-width:980px"><thead><tr><th>Request Code</th><th>Request Type</th><th>Item Type</th><th>Related Record(s)</th><th>Submitted</th><th>Status</th><th>Approval Stage</th><th>Last Update</th><th>Rating</th><th></th></tr></thead><tbody>'+(list.length?list.map(function(r){return'<tr><td class="adv-code">'+esc(r.code||r.id)+'</td><td>'+esc(typeLabel(r))+'</td><td>'+esc(r.category||r.relatedType||'—')+'</td><td>'+esc(relatedText(r))+'</td><td>'+formatDate(r.createdAt,true)+'</td><td>'+statusBadge(r.status)+'</td><td><span class="adv-workflow-stage">'+esc(workflowLabel(r))+'</span></td><td>'+formatDate(r.updatedAt||r.respondedAt||r.createdAt,true)+'</td><td>'+stars(r.rating)+(r.ratingComment?'<div class="adv-rating-comment-mini">'+esc(r.ratingComment)+'</div>':'')+'</td><td><button class="adv-btn secondary" onclick="window._advOpenRequest(\''+esc(r.id)+'\')">Show</button></td></tr>';}).join(''):'<tr><td colspan="10"><div class="adv-empty">No requests have been submitted yet.</div></td></tr>')+'</tbody></table></div></div>';}
  function managerReviewReturnFields(){return [
    ['title','Request Title'],['details','Request Details'],['related','Related Record / Proposed Item'],['priority','Priority']
  ];}
  function managerReviewFieldLabel(k){var m={title:'Request Title',details:'Request Details',related:'Related Record / Proposed Item',priority:'Priority'};return m[k]||k;}
  function managerReviewReturnSelector(selected){
    selected=Array.isArray(selected)?selected:[];
    return '<div class="adv-manager-return-fields"><div class="adv-manager-return-title">Select the fields the requester must update *</div><div class="adv-manager-return-grid">'+managerReviewReturnFields().map(function(x){return '<label><input type="checkbox" data-adv-return-field value="'+esc(x[0])+'" '+(selected.indexOf(x[0])>=0?'checked':'')+'> <span>'+esc(x[1])+'</span></label>';}).join('')+'</div></div>';
  }
  function managerRequestsHtml(){
    var review=records.filter(isManagerApprovalRecord).filter(function(r){return String(r&&r.workflowStage||'')==='pending_department_manager';});
    var risk=(managerRiskRecords||[]).filter(function(r){return String(r&&r.status||'').toLowerCase()==='pending_manager';});
    function card(x){
      var isReview=x.kind==='review';
      var code=x.code||x.id, requester=x.requester||'—', label=x.label||'—', date=x.date||'—';
      return '<div class="adv-manager-request-card" data-adv-manager-row="'+esc(x.id)+'"><div class="adv-manager-request-head"><div><strong>'+esc(code)+'</strong><span>'+esc(label)+'</span></div><span class="adv-manager-pending">Pending Department Manager Approval</span></div><div class="adv-manager-request-meta"><div><small>Requester</small><b>'+esc(requester)+'</b></div><div><small>Submitted</small><b>'+esc(date)+'</b></div></div><div class="adv-manager-card-actions">'+
        '<button class="adv-btn good" type="button" onclick="window._advManagerQuickAction(\''+esc(x.id)+'\',\'approve\',this)">Approve to Super Admin</button>'+
        '<button class="adv-btn warn" type="button" onclick="window._advManagerQuickAction(\''+esc(x.id)+'\',\'return\',this)">Return</button>'+
        '<button class="adv-btn danger" type="button" onclick="window._advManagerQuickAction(\''+esc(x.id)+'\',\'reject\',this)">Reject</button>'+
        '<button class="adv-btn secondary" type="button" onclick="'+(isReview?'window._advOpenRequest(\''+esc(x.id)+'\')':'window._grcRiskOpenProfile(\''+esc(x.id)+'\')')+'">View Details</button></div><div class="adv-manager-inline-decision-slot"></div></div>';
    }
    var reviewRows=review.map(function(r){return{kind:'review',id:r.id,code:r.code||r.id,requester:r.userName||r.userEmail||'—',label:typeLabel(r),date:formatDate(r.createdAt,true),time:timeMs(r.createdAt)||Date.parse(r.createdAtIso||0)||0};});
    var riskRows=risk.map(function(r){return{kind:'risk',id:r.id,code:r.requestCode||r.id,requester:r.submittedByName||r.submittedByEmail||'—',label:(String(r.recordType||'risk').toLowerCase()==='incident'?'Incident':'Risk')+' · '+String(r.operation||'request').replace(/^./,function(c){return c.toUpperCase();}),date:formatDate(r.createdAt||r.createdAtIso,true),time:timeMs(r.createdAt)||Date.parse(r.createdAtIso||0)||0};});
    reviewRows.sort(function(a,b){return b.time-a.time;});riskRows.sort(function(a,b){return b.time-a.time;});
    var error=lastLoadError?'<div class="adv-card" style="margin-bottom:12px;border-color:#f1b6b6;background:#fff7f7;color:#991b1b"><strong>Department approval sync error:</strong> '+esc(lastLoadError)+'</div>':'';
    function section(title,subtitle,rows){return '<div class="adv-card adv-manager-section" style="margin-bottom:14px"><div class="adv-register-toolbar"><div><h3>'+esc(title)+'</h3><p>'+esc(subtitle)+'</p></div><div class="adv-filter-note"><b>'+rows.length+'</b> Pending</div></div><div class="adv-manager-request-list">'+(rows.length?rows.map(card).join(''):'<div class="adv-empty">No pending requests in this section.</div>')+'</div></div>';}
    return error+
      section('Risk & Incident Register Approval Requests','Risk and Incident changes awaiting your approval.',riskRows)+
      section('Review & Development Approval Requests','Existing Item Review & Update and New Item requests awaiting your approval.',reviewRows)+
      ownRequestsHtml();
  }
  function managerQuickSlot(btn){var row=btn&&btn.closest&&btn.closest('[data-adv-manager-review-row]');return row&&row.querySelector?row.querySelector('.adv-manager-inline-decision-slot'):null;}
  function clearManagerQuickPanels(){document.querySelectorAll('.adv-manager-inline-decision-slot').forEach(function(slot){slot.innerHTML='';});}
  window._advManagerQuickCancel=function(btn){var panel=btn&&btn.closest&&btn.closest('.adv-manager-inline-decision');if(panel)panel.remove();};
  window._advManagerQuickAction=async function(id,action,btn){
    if(!apiReady('_advisoryManagerAction'))return toast('Department approval service is unavailable.');
    action=String(action||'');if(['approve','return','reject'].indexOf(action)<0)return;
    var row=btn&&btn.closest&&btn.closest('[data-adv-manager-row]'),slot=row&&row.querySelector('.adv-manager-inline-decision-slot');if(!slot)return;
    clearManagerQuickPanels();
    if(action==='approve'){
      var siblings=btn.closest('.adv-manager-card-actions');if(siblings)siblings.querySelectorAll('button').forEach(function(x){x.disabled=true;});
      var old=btn.textContent;btn.textContent='Approving…';
      try{await window._advisoryManagerAction(id,'approve','',[]);records=records.filter(function(r){return String(r.id)!==String(id);});renderView();if(typeof window._grcRiskInjectManagerQueue==='function')window._grcRiskInjectManagerQueue(managerRiskRecords,records.filter(isManagerApprovalRecord));toast('Request approved and forwarded to Super Admin.');}catch(e){if(siblings)siblings.querySelectorAll('button').forEach(function(x){x.disabled=false;});btn.textContent=old;toast(String(e&&e.message||e));}
      return;
    }
    var isReturn=action==='return',title=isReturn?'Return Request':'Reject Request',help=isReturn?'Select what the requester must correct and add a clear note.':'Add the rejection reason. This request will not be forwarded to Super Admin.',label=isReturn?'Return note *':'Rejection reason *',confirm=isReturn?'Confirm Return':'Confirm Reject';
    var selected=[];
    slot.innerHTML='<div class="adv-manager-inline-decision '+(isReturn?'warn':'danger')+'" style="margin-top:8px;padding:10px;border:1px solid '+(isReturn?'#e9c77a':'#efb0b0')+';border-radius:10px;background:'+(isReturn?'#fffaf0':'#fff7f7')+'"><strong style="display:block;margin-bottom:4px">'+esc(title)+'</strong><small style="display:block;margin-bottom:8px">'+esc(help)+'</small>'+(isReturn?managerReviewReturnSelector(selected):'')+'<label style="display:block;font-weight:800;font-size:10px;margin-bottom:4px">'+esc(label)+'</label><textarea rows="3" style="width:100%;box-sizing:border-box" placeholder="Enter the note here..."></textarea><div class="adv-rating-error" aria-live="polite"></div><div style="display:flex;gap:7px;margin-top:8px"><button class="adv-btn '+(isReturn?'warn':'danger')+'" type="button" onclick="window._advManagerQuickSubmit(\''+esc(id)+'\',\''+action+'\',this)">'+esc(confirm)+'</button><button class="adv-btn ghost" type="button" onclick="window._advManagerQuickCancel(this)">Cancel</button></div></div>';
    var ta=slot.querySelector('textarea');if(ta)setTimeout(function(){ta.focus();},20);
  };
  window._advManagerQuickSubmit=async function(id,action,btn){
    var panel=btn&&btn.closest&&btn.closest('.adv-manager-inline-decision');if(!panel)return;
    var ta=panel.querySelector('textarea'),comment=String(ta&&ta.value||'').trim(),err=panel.querySelector('.adv-rating-error');
    var fields=[];panel.querySelectorAll('[data-adv-return-field]:checked').forEach(function(x){fields.push(String(x.value||''));});
    if(action==='return'&&!fields.length){if(err)err.textContent='Select at least one field that the requester must update.';return;}
    if(!comment){if(err)err.textContent=action==='return'?'Enter a return note before sending the request back to the requester.':'Enter a rejection reason before rejecting the request.';if(ta)ta.focus();return;}
    if(err)err.textContent='';panel.querySelectorAll('button,textarea,input').forEach(function(x){x.disabled=true;});var old=btn.textContent;btn.textContent=action==='return'?'Returning…':'Rejecting…';
    try{await window._advisoryManagerAction(id,action,comment,fields);records=records.filter(function(r){return String(r.id)!==String(id);});renderView();if(typeof window._grcRiskInjectManagerQueue==='function')window._grcRiskInjectManagerQueue(managerRiskRecords,records.filter(isManagerApprovalRecord));toast(action==='return'?'Request returned for update.':'Request rejected. It will not be forwarded to Super Admin.');}catch(e){panel.querySelectorAll('button,textarea,input').forEach(function(x){x.disabled=false;});btn.textContent=old;if(err)err.textContent=String(e&&e.message||e);}
  };

  function managerActions(r){return'<div class="adv-card adv-manager-action-card" style="margin-top:12px"><h3 class="adv-card-title">Department Manager Approval</h3><p class="adv-rating-help">Choose one action: approve and send to Super Admin, return the request for update, or reject.</p><div class="adv-form"><div class="adv-field full"><label>Return / Rejection Note</label><div id="advManagerReturnFields">'+managerReviewReturnSelector([])+'</div><textarea id="advManagerComment" placeholder="Required for Return or Reject; not required for approval"></textarea><div id="advManagerError" class="adv-rating-error"></div></div><div class="adv-field full"><div class="adv-modal-actions" style="justify-content:flex-start;gap:8px;flex-wrap:wrap"><button class="adv-btn good" type="button" onclick="window._advManagerAction(\'approve\',this)">Approve to Super Admin</button><button class="adv-btn warn" type="button" onclick="window._advManagerAction(\'return\',this)">Return</button><button class="adv-btn danger" type="button" onclick="window._advManagerAction(\'reject\',this)">Reject</button></div></div></div></div>';} 
  window._advManagerAction=async function(action,btn){if(!selectedRequest||!apiReady('_advisoryManagerAction'))return;var comment=String((document.getElementById('advManagerComment')||{}).value||'').trim(),err=document.getElementById('advManagerError'),fields=[];document.querySelectorAll('#advModal [data-adv-return-field]:checked').forEach(function(x){fields.push(String(x.value||''));});if(action==='return'&&!fields.length){if(err)err.textContent='Select at least one field that the requester must update.';return;}if((action==='return'||action==='reject')&&!comment){if(err)err.textContent=action==='return'?'Enter a return note before sending the request back to the requester.':'Enter a rejection reason before rejecting the request.';return;}if(err)err.textContent='';var old=btn&&btn.textContent;if(btn){btn.disabled=true;btn.textContent=action==='approve'?'Approving…':action==='return'?'Returning…':'Rejecting…';}try{await window._advisoryManagerAction(selectedRequest.id,action,comment,fields);records=records.filter(function(r){return String(r&&r.id)!==String(selectedRequest.id);});closeModal();renderView();if(typeof window._grcRiskInjectManagerQueue==='function')window._grcRiskInjectManagerQueue(managerRiskRecords,records.filter(isManagerApprovalRecord));toast(action==='approve'?'Request approved and forwarded to Super Admin.':action==='return'?'Request returned for update.':'Request rejected. It will not be forwarded to Super Admin.');}catch(e){if(btn){btn.disabled=false;btn.textContent=old||'Submit';}if(err)err.textContent=String(e&&e.message||e);else toast(String(e&&e.message||e));}};
  function adminActions(r){
    var stage=workflowStage(r);
    if(stage==='pending_super_admin'){
      return '<div class="adv-card" style="margin-top:12px"><h3 class="adv-card-title">Super Admin Approval</h3><p class="adv-rating-help">Choose one action: approve, return for update, or reject. A note is required for Return and Reject.</p><div class="adv-form"><div class="adv-field full"><label>Return / Rejection Note</label><textarea id="advAdminReply" placeholder="Required for Return or Reject; optional for Approve"></textarea><div id="advAdminError" class="adv-rating-error"></div></div><div class="adv-field full"><div class="adv-modal-actions" style="justify-content:flex-start;gap:8px;flex-wrap:wrap"><button class="adv-btn good" type="button" onclick="window._advAdminDecision(\'approve\',this)">Approve</button><button class="adv-btn warn" type="button" onclick="window._advAdminDecision(\'return\',this)">Return</button><button class="adv-btn danger" type="button" onclick="window._advAdminDecision(\'reject\',this)">Reject</button></div></div></div></div>';
    }
    if(['pending_department_manager','returned_requester','rejected_manager'].indexOf(stage)>=0)return '';
    var canClose=statusKey(r.status)!=='closed';return'<div class="adv-card" style="margin-top:12px"><h3 class="adv-card-title">Super Admin Action</h3><div class="adv-form"><div class="adv-field full"><label>Response / Recommendation</label><textarea id="advAdminReply" placeholder="Write the response shown to the requester"></textarea></div><div class="adv-field full"><label>Attachment (optional)</label><input id="advAdminAttachment" type="file"></div><div class="adv-field full"><div class="adv-modal-actions" style="justify-content:flex-start"><button class="adv-btn primary" onclick="window._advAdminAction(\'respond\')">Send Response</button><button class="adv-btn warn" onclick="window._advAdminAction(\'request_info\')">Request More Information</button>'+(canClose?'<button class="adv-btn good" onclick="window._advAdminAction(\'close\')">Close Request</button>':'')+'<select id="advExceptionalAction" style="padding:8px 9px;border:1px solid #d7e2e7;border-radius:9px;font-size:9px"><option value="">Exceptional Action</option><option value="duplicate">Mark as Duplicate</option><option value="out_of_scope">Mark as Out of Scope</option><option value="knowledge_guide">Direct to Knowledge Guide</option></select><button class="adv-btn ghost" onclick="window._advApplyExceptional()">Apply</button></div></div></div></div>';
  }
  window._advAdminDecision=async function(action,btn){
    if(!selectedRequest||!apiReady('_advisoryAdminAction'))return;
    var comment=String((document.getElementById('advAdminReply')||{}).value||'').trim(),err=document.getElementById('advAdminError');
    if((action==='return'||action==='reject')&&!comment){if(err)err.textContent=action==='return'?'Enter a return note before sending the request back.':'Enter a rejection reason before rejecting the request.';return;}
    if(err)err.textContent='';var old=btn&&btn.textContent;if(btn){btn.disabled=true;btn.textContent=action==='approve'?'Approving…':action==='return'?'Returning…':'Rejecting…';}
    try{await window._advisoryAdminAction(selectedRequest.id,action,{text:comment},null);closeModal();await refreshAfterMutation();toast(action==='approve'?'Request approved by Super Admin.':action==='return'?'Request returned for update.':'Request rejected by Super Admin.');}
    catch(e){if(btn){btn.disabled=false;btn.textContent=old||'Submit';}if(err)err.textContent=String(e&&e.message||e);else toast(String(e&&e.message||e));}
  };
  window._advAdminAction=async function(action){if(!selectedRequest||!apiReady('_advisoryAdminAction'))return;var reply=String((document.getElementById('advAdminReply')||{}).value||'').trim(),file=(document.getElementById('advAdminAttachment')||{}).files&&document.getElementById('advAdminAttachment').files[0];if((action==='respond'||action==='request_info')&&!reply)return toast('Enter a response or information request first.');try{await window._advisoryAdminAction(selectedRequest.id,action,{text:reply},file||null);closeModal();await refreshAfterMutation();toast(action==='close'?'Request closed. The requester will be prompted to rate the service.':'Request updated successfully.');}catch(e){toast(String(e&&e.message||e));}};
  window._advApplyExceptional=function(){var v=String((document.getElementById('advExceptionalAction')||{}).value||'');if(!v)return toast('Select an exceptional action.');window._advAdminAction(v);};
  function returnedRequesterEditor(r){var note=String(r&&r.managerComment||r&&r.returnNote||'').trim(),fields=Array.isArray(r&&r.returnFields)?r.returnFields:[],isNew=normalizedType(r)==='new',priority=String(r&&r.priority||'Medium');return'<div class="adv-card adv-manager-action-card" style="margin-top:12px"><h3 class="adv-card-title">Returned by Department Manager</h3><p class="adv-rating-help">Update the request below, then resubmit it to the Department Manager.</p>'+(fields.length?'<div class="adv-personal-note" style="margin-bottom:10px"><strong>Fields to update:</strong> '+esc(fields.map(managerReviewFieldLabel).join(' · '))+'</div>':'')+(note?'<div class="adv-personal-note" style="margin-bottom:10px"><strong>Manager note:</strong> '+esc(note)+'</div>':'')+'<div class="adv-form"><div class="adv-field full"><label>Request Title *</label><input id="advReturnedTitle" value="'+esc(r.title||'')+'"></div><div class="adv-field full"><label>Request Details *</label><textarea id="advReturnedDetails">'+esc(r.details||'')+'</textarea></div>'+(isNew?'<div class="adv-field full"><label>Proposed '+esc(r.category||r.relatedType||'Item')+' Name(s) *</label><textarea id="advReturnedRelatedNew">'+esc(r.relatedNewText||'')+'</textarea></div>':'')+'<div class="adv-field"><label>Priority</label><select id="advReturnedPriority"><option '+(priority==='Low'?'selected':'')+'>Low</option><option '+(priority==='Medium'?'selected':'')+'>Medium</option><option '+(priority==='High'?'selected':'')+'>High</option></select></div><div class="adv-field full"><label>Attachment (optional)</label><input id="advReturnedAttachment" type="file"><small>Maximum file size: 5 MB.</small></div><div id="advReturnedError" class="adv-rating-error"></div><div class="adv-field full"><button class="adv-btn good" type="button" onclick="window._advResubmitReturned(this)">Save & Resubmit to Department Manager</button></div></div></div>';}
  window._advResubmitReturned=async function(btn){if(!selectedRequest||!apiReady('_advisoryRequesterAction'))return;var title=String((document.getElementById('advReturnedTitle')||{}).value||'').trim(),details=String((document.getElementById('advReturnedDetails')||{}).value||'').trim(),priority=String((document.getElementById('advReturnedPriority')||{}).value||'Medium'),relatedEl=document.getElementById('advReturnedRelatedNew'),relatedNewText=relatedEl?String(relatedEl.value||'').trim():String(selectedRequest.relatedNewText||''),file=(document.getElementById('advReturnedAttachment')||{}).files&&document.getElementById('advReturnedAttachment').files[0],err=document.getElementById('advReturnedError');if(!title){if(err)err.textContent='Request Title is required.';return;}if(!details){if(err)err.textContent='Request Details are required.';return;}if(normalizedType(selectedRequest)==='new'&&!relatedNewText){if(err)err.textContent='Proposed item name is required.';return;}if(file&&file.size>5*1024*1024){if(err)err.textContent='The attachment must be 5 MB or smaller.';return;}if(err)err.textContent='';var old=btn&&btn.textContent;if(btn){btn.disabled=true;btn.textContent='Resubmitting…';}try{await window._advisoryRequesterAction(selectedRequest.id,'resubmit',{title:title,details:details,priority:priority,relatedNewText:relatedNewText},file||null);closeModal();await refreshAfterMutation();toast('Request updated and resubmitted to the Department Manager.');}catch(e){if(btn){btn.disabled=false;btn.textContent=old||'Save & Resubmit to Department Manager';}if(err)err.textContent=String(e&&e.message||e);else toast(String(e&&e.message||e));}};
  function requesterActions(r){var h='',stage=String(r.workflowStage||r.status);if(stage==='returned_requester')h+=returnedRequesterEditor(r);if(stage==='awaiting_requester_information')h+='<div class="adv-card" style="margin-top:12px"><h3 class="adv-card-title">Provide Additional Information</h3><div class="adv-form"><div class="adv-field full"><label>Clarification *</label><textarea id="advClarification"></textarea></div><div class="adv-field full"><label>Attachment (optional)</label><input id="advClarificationFile" type="file"></div><div class="adv-field full"><button class="adv-btn primary" onclick="window._advSendClarification()">Send Clarification</button></div></div></div>';if(String(r.workflowStage||r.status)==='responded')h+='<div class="adv-card" style="margin-top:12px"><h3 class="adv-card-title">Confirm Completion</h3><button class="adv-btn good" onclick="window._advConfirmComplete()">Confirm Completed</button></div>';if(statusKey(r.status)!=='closed')h+='<div class="adv-requester-cancel-wrap"><button class="adv-btn danger" onclick="window._advShowCancelConfirm()">Cancel Request</button><div id="advCancelConfirmSlot"></div></div>';if(canRateReview(r)&&!Number(r.rating))h+='<div class="adv-card adv-rating-card" style="margin-top:12px"><h3 class="adv-card-title">Rate Your Experience</h3><p class="adv-rating-help">Choose the number of stars, add an optional comment, then submit your rating.</p><div class="adv-stars adv-stars-select">'+[1,2,3,4,5].map(function(n){return'<button type="button" class="adv-star" data-adv-rating="'+n+'" onclick="window._advSelectRating('+n+')" aria-label="'+n+' star rating">★</button>';}).join('')+'</div><div id="advRatingSelected" class="adv-rating-selected">No rating selected</div><textarea id="advRatingComment" class="adv-rating-comment" placeholder="Add a comment (optional)"></textarea><div id="advRatingError" class="adv-rating-error"></div><button id="advRatingSubmit" class="adv-btn primary" type="button" onclick="window._advSubmitRating(this)">Submit Rating</button></div>';return h;}
  window._advSendClarification=async function(){var text=String((document.getElementById('advClarification')||{}).value||'').trim(),file=(document.getElementById('advClarificationFile')||{}).files&&document.getElementById('advClarificationFile').files[0];if(!text)return toast('Enter the clarification first.');try{await window._advisoryRequesterAction(selectedRequest.id,'clarify',{text:text},file||null);closeModal();await refreshAfterMutation();toast('Clarification sent.');}catch(e){toast(String(e&&e.message||e));}};
  window._advConfirmComplete=async function(){try{await window._advisoryRequesterAction(selectedRequest.id,'complete',{},null);closeModal();await refreshAfterMutation();toast('Request marked as Completed.');}catch(e){toast(String(e&&e.message||e));}};
  window._advShowCancelConfirm=function(){var slot=document.getElementById('advCancelConfirmSlot');if(!slot)return;if(slot.innerHTML.trim()){slot.innerHTML='';return;}slot.innerHTML='<div class="adv-inline-confirm danger" role="alertdialog" aria-label="Cancel request confirmation"><div class="adv-inline-confirm-icon">!</div><div class="adv-inline-confirm-copy"><strong>Cancel this request?</strong><span>This request will be cancelled and no further action will be taken.</span></div><div class="adv-inline-confirm-actions"><button class="adv-btn ghost" type="button" onclick="window._advHideCancelConfirm()">Keep Request</button><button class="adv-btn danger" type="button" onclick="window._advCancelRequest(this)">Confirm Cancel</button></div></div>';};
  window._advHideCancelConfirm=function(){var slot=document.getElementById('advCancelConfirmSlot');if(slot)slot.innerHTML='';};
  window._advCancelRequest=async function(btn){if(!selectedRequest||!apiReady('_advisoryRequesterAction'))return;var oldText=btn&&btn.textContent;if(btn){btn.disabled=true;btn.textContent='Cancelling…';}try{await window._advisoryRequesterAction(selectedRequest.id,'cancel',{},null);closeModal();await refreshAfterMutation();toast('Request cancelled.');}catch(e){if(btn){btn.disabled=false;btn.textContent=oldText||'Confirm Cancel';}var slot=document.getElementById('advCancelConfirmSlot');if(slot){var box=slot.querySelector('.adv-inline-confirm');if(box)box.classList.add('has-error');var copy=slot.querySelector('.adv-inline-confirm-copy span');if(copy)copy.textContent=String(e&&e.message||e);}}};
  window._advSelectRating=function(rating){selectedRating=Math.max(1,Math.min(5,Number(rating||0)));document.querySelectorAll('#advModal [data-adv-rating]').forEach(function(btn){var n=Number(btn.getAttribute('data-adv-rating')||0);btn.classList.toggle('selected',n<=selectedRating);btn.setAttribute('aria-pressed',n<=selectedRating?'true':'false');});var label=document.getElementById('advRatingSelected');if(label)label.textContent='Selected rating: '+selectedRating+' out of 5';var err=document.getElementById('advRatingError');if(err)err.textContent='';};
  window._advSubmitRating=async function(btn){if(!selectedRequest||!apiReady('_advisoryRate'))return;var err=document.getElementById('advRatingError');if(!selectedRating){if(err)err.textContent='Select a star rating before submitting.';return;}var comment=String((document.getElementById('advRatingComment')||{}).value||'').trim(),old=btn&&btn.textContent;if(btn){btn.disabled=true;btn.textContent='Submitting…';}try{await window._advisoryRate(selectedRequest.id,selectedRating,comment);closeModal();await refreshAfterMutation();toast('Thank you. Your rating was saved.');}catch(e){if(btn){btn.disabled=false;btn.textContent=old||'Submit Rating';}if(err)err.textContent=String(e&&e.message||e);}};
  function showRatingNotification(){try{document.dispatchEvent(new CustomEvent('grc:feedbackRefresh'));}catch(_){}}
  function closeModal(clear){var m=document.getElementById('advModal');if(m)m.remove();document.body.classList.remove('adv-modal-open');if(clear!==false)selectedRequest=null;}
  window._advCloseModal=function(){closeModal();};
  function ensureManagerQueueStyles(){if(document.getElementById('_advManagerQueueStyles'))return;var st=document.createElement('style');st.id='_advManagerQueueStyles';st.textContent='.adv-manager-section{overflow:hidden}.adv-manager-request-list{display:flex;flex-direction:column;gap:10px}.adv-manager-request-card{border:1px solid #dce6eb;border-radius:14px;background:#fff;padding:13px;box-shadow:0 5px 16px rgba(23,63,95,.04)}.adv-manager-request-head{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.adv-manager-request-head strong{display:block;font-size:12px;color:#173f5f}.adv-manager-request-head span:not(.adv-manager-pending){display:block;margin-top:4px;font-size:9.5px;color:#6a808d}.adv-manager-pending{white-space:nowrap;padding:5px 8px;border-radius:999px;background:#fff4df;color:#a85c06;border:1px solid #f2d5a5;font-size:9px;font-weight:900}.adv-manager-request-meta{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:11px;padding:10px;border-radius:10px;background:#f7fafb}.adv-manager-request-meta small{display:block;color:#718590;font-size:8.5px}.adv-manager-request-meta b{display:block;color:#2f4f61;font-size:9.5px;margin-top:3px}.adv-manager-card-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:11px}.adv-manager-return-fields{margin:8px 0;padding:9px;border:1px solid #e6d5a8;border-radius:9px;background:#fffdf7}.adv-manager-return-title{font-size:9.5px;font-weight:900;color:#7c5a16;margin-bottom:7px}.adv-manager-return-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px}.adv-manager-return-grid label{display:flex;align-items:center;gap:6px;padding:7px;border:1px solid #e2e8ec;border-radius:8px;background:#fff;font-size:9px;font-weight:800;color:#35566a}.adv-manager-return-grid input{width:14px;height:14px}@media(max-width:650px){.adv-manager-request-head{flex-direction:column}.adv-manager-request-meta{grid-template-columns:1fr}.adv-manager-return-grid{grid-template-columns:1fr}}';document.head.appendChild(st);}
  var _oldRenderView=renderView;renderView=function(){ensureManagerQueueStyles();return _oldRenderView.apply(this,arguments);};

})();
