/* ======================================================================
   QUMC Review & Development Center — Performance + GRC
   Build: 2026-07-27 v66
   Request types:
   1) Existing Item Review & Update
   2) New Item Request
   ====================================================================== */
(function(){
  'use strict';

  var records=[],currentPlatform='grc',currentRootId='advRootGrc',currentView='dashboard';
  var dashboardFilter='all',departmentFilter='',dashboardSearch='',dashboardStatus='';
  var adminSearch='',adminStatus='',adminDepartment='',loading=false,lastLoadError='',selectedRequest=null;

  var STATUS_LABELS={
    under_review:'Under Review',in_progress:'In Progress',awaiting_requester_information:'Awaiting Information from Requester',
    responded:'Responded',completed:'Completed',closed:'Closed',duplicate:'Duplicate',cancelled:'Cancelled by Requester',
    out_of_scope:'Out of Scope',knowledge_guide:'Directed to Knowledge Guide'
  };
  var TYPE_LABELS={edit_review:'Existing Item Review & Update',new:'New Item Request',clarification:'Existing Item Review & Update',review:'Existing Item Review & Update'};
  var PLATFORM_LABELS={performance:'Performance',grc:'GRC'};
  var ITEM_TYPES={
    performance:[
      {value:'kpi_definition',label:'KPI Definition / Indicator',key:'kpis'},
      {value:'kpi_card',label:'KPI Card',key:'kpis'},
      {value:'target',label:'Target',key:'kpis'},
      {value:'formula',label:'Calculation Formula',key:'kpis'},
      {value:'data_source',label:'Data Source',key:'kpis'},
      {value:'quarterly_result',label:'Quarterly Result',key:'kpis'},
      {value:'gap_analysis',label:'Gap Analysis',key:'kpis'},
      {value:'corrective_action',label:'Corrective Action',key:'kpis'},
      {value:'ownership',label:'KPI Ownership / Responsibility',key:'kpis'},
      {value:'dashboard_view',label:'Dashboard / Visualization',key:'kpis'}
    ],
    grc:[
      {value:'policy',label:'Policy / Procedure',key:'policies'},
      {value:'form',label:'Form / Checklist',key:'forms'},
      {value:'plan',label:'Operational Plan',key:'plans'},
      {value:'risk',label:'Risk Register Entry',key:'risks'},
      {value:'incident',label:'Incident Register Entry',key:'incidents'},
      {value:'code',label:'Emergency Code Record',key:'codes'},
      {value:'action',label:'Action Plan',key:'actions'},
      {value:'initiative',label:'Initiative',key:'initiatives'},
      {value:'manual',label:'Manual / Guideline',key:'manuals'},
      {value:'report',label:'Report',key:'reports'},
      {value:'cbahi',label:'CBAHI Requirement',key:'cbahi'},
      {value:'jci',label:'JCI Requirement',key:'jci'}
    ]
  };
  var DEPARTMENTS={
    safety:{name:'Safety',code:'SAF'},maintenance:{name:'Maintenance',code:'MNT'},housekeeping:{name:'Housekeeping',code:'HSK'},
    laundry:{name:'Laundry',code:'LND'},projects:{name:'Project Management',code:'PRJ'},governance:{name:'Governance & Performance',code:'GOV'},division:{name:'Governance & Performance',code:'GOV'}
  };

  function esc(v){return String(v==null?'':v).replace(/[&<>'"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c];});}
  function role(){return String(window._fbRole||window.currentUserRole||'viewer').trim().toLowerCase().replace(/[\s-]+/g,'_');}
  function isAdmin(){return role()==='admin'||role()==='super_admin';}
  function isSuperAdmin(){return role()==='super_admin';}
  function userEmail(){return String(window._fbUser||window.currentUserEmail||'').toLowerCase().trim();}
  function userDepartmentKey(){
    var raw=String(window._fbDept||window.currentUserDept||'').trim().toLowerCase().replace(/[\s&/-]+/g,'_');
    if(raw.indexOf('safe')>=0)return'safety';if(raw.indexOf('maint')>=0)return'maintenance';if(raw.indexOf('laund')>=0)return'laundry';
    if(raw.indexOf('house')>=0||raw.indexOf('clean')>=0)return'housekeeping';if(raw.indexOf('project')>=0)return'projects';
    if(raw.indexOf('govern')>=0||raw.indexOf('performance')>=0||raw.indexOf('division')>=0)return'governance';return DEPARTMENTS[raw]?raw:'governance';
  }
  function departmentName(k){return(DEPARTMENTS[k]&&DEPARTMENTS[k].name)||String(k||'—');}
  function departmentCode(k){return(DEPARTMENTS[k]&&DEPARTMENTS[k].code)||'FMS';}
  function root(){return document.getElementById(currentRootId);}
  function host(){var r=root();return r&&r.querySelector('#advViewHost');}
  function recordPlatform(r){return String(r&&r.platform||'grc').toLowerCase()==='performance'?'performance':'grc';}
  function normalizedType(r){var t=String(r&&r.requestType||'');return t==='new'?'new':'edit_review';}
  function typeLabel(r){return TYPE_LABELS[String(r&&r.requestType||'')]||TYPE_LABELS[normalizedType(r)];}
  function isRelevantRecord(r){return r&&recordPlatform(r)===currentPlatform&&String(r.serviceType||'review_guidance')!=='session';}
  function formatDate(v,withTime){if(!v)return'—';var d=v&&v.toDate?v.toDate():new Date(v);if(isNaN(d.getTime()))return'—';try{return new Intl.DateTimeFormat('en-GB',withTime?{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}:{day:'2-digit',month:'short',year:'numeric'}).format(d);}catch(_){return d.toLocaleString();}}
  function timeMs(v){if(!v)return 0;var d=v&&v.toDate?v.toDate():new Date(v);return isNaN(d.getTime())?0:d.getTime();}
  function responseMinutes(r){if(Number.isFinite(Number(r.responseMinutes)))return Number(r.responseMinutes);var a=timeMs(r.createdAt),b=timeMs(r.firstRespondedAt||r.respondedAt);return a&&b?Math.max(0,Math.round((b-a)/60000)):null;}
  function durationText(m){if(m==null)return'Not Responded';if(m<60)return m+' min';var h=Math.floor(m/60),x=m%60;if(h<24)return h+' hr'+(h===1?'':'s')+(x?' '+x+' min':'');var d=Math.floor(h/24),rh=h%24;return d+' day'+(d===1?'':'s')+(rh?' '+rh+' hrs':'');}
  function statusLabel(s){return STATUS_LABELS[s]||String(s||'—');}
  function statusBadge(s){return'<span class="adv-status '+esc(s)+'">'+esc(statusLabel(s))+'</span>';}
  function stars(v){var n=Number(v||0);return n?'<span title="'+n+' out of 5">'+('★'.repeat(n))+('☆'.repeat(Math.max(0,5-n)))+'</span>':'—';}
  function toast(message){var r=root()||document.body,old=r.querySelector&&r.querySelector('.adv-toast');if(old)old.remove();var e=document.createElement('div');e.className='adv-toast';e.textContent=message;r.appendChild(e);setTimeout(function(){e.remove();},3200);}
  function apiReady(n){return typeof window[n]==='function';}
  function audit(a,d){try{if(typeof window.addAudit==='function')window.addAudit(a,d);else if(typeof window._recordAuditDirect==='function')window._recordAuditDirect(a,d);}catch(_){}}
  function approved(r){return r.status==='completed'||r.status==='closed';}
  function isOpen(r){return['under_review','in_progress','awaiting_requester_information','responded'].indexOf(r.status)>=0;}

  function moduleCard(id,icon,title,desc,sa){return'<button type="button" class="adv-module-card '+(currentView===id?'is-active':'')+'" data-adv-view="'+id+'" onclick="window._advSwitchView(\''+id+'\')">'+(sa?'<span class="adv-sa-pill">SUPER ADMIN</span>':'')+'<span class="adv-module-icon">'+icon+'</span><h3>'+title+'</h3><p>'+desc+'</p></button>';}
  function pageSkeleton(platform,rootId){
    currentPlatform=platform;currentRootId=rootId;var label=PLATFORM_LABELS[platform];
    return'<div class="adv-platform-root" id="'+rootId+'" data-adv-platform="'+platform+'"><div class="adv-shell">'+
      '<div class="grc-hero adv-hero"><div class="grc-hero-row"><div><div class="grc-eyebrow">'+label+' · INTERNAL REVIEW & DEVELOPMENT SERVICE</div><h1>Review & Development Center</h1><p>Request an update and professional review for an existing record, or submit a request for a new record. Available items are limited to this platform and the requester\'s department.</p></div><div class="grc-hero-actions"><button class="grc-primary-btn" onclick="window._advOpenGuidanceRequest()">＋ Submit Request</button></div></div></div>'+
      '<div class="adv-privacy-note"><span class="adv-privacy-icon">i</span><div><strong>Before submitting a request</strong>Choose Existing Item Review & Update for an item already listed, or New Item Request for an item that does not yet exist. Request details and attachments are available only to Admin and Super Admin.</div></div>'+
      '<div class="adv-module-grid">'+moduleCard('dashboard','▦','Review & Development Dashboard','Approval indicators and a non-personal request register scoped to this platform and department.')+moduleCard('requests','✦','Review & Development Requests',isAdmin()?'Review requests, request information, respond and close completed cases.':'Submit and follow Existing Item Review & Update or New Item Request cases.')+(isSuperAdmin()?moduleCard('management','⚙','Center Management','Request types, item scopes and automatic workflow.',true):'')+'</div>'+
      '<div id="advViewHost"><div class="adv-loading">Loading Review & Development Center…</div></div></div></div>';
  }
  window._grcAdvisoryPage=function(){return pageSkeleton('grc','advRootGrc');};
  window._grcAdvisoryMount=function(){mount('grc','advRootGrc');};
  window._performanceAdvisoryMount=function(){var h=document.getElementById('performanceAdvisoryRoot');if(!h)return;if(!h.querySelector('#advRootPerformance'))h.innerHTML=pageSkeleton('performance','advRootPerformance');mount('performance','advRootPerformance');};
  function mount(platform,rootId){currentPlatform=platform;currentRootId=rootId;currentView='dashboard';dashboardFilter='all';departmentFilter='';loadRecords();}
  window._advSwitchView=function(view){if(view==='management'&&!isSuperAdmin())return;currentView=view;dashboardSearch='';dashboardStatus='';adminSearch='';adminStatus='';adminDepartment='';var r=root();if(r)r.querySelectorAll('.adv-module-card').forEach(function(x){x.classList.toggle('is-active',x.getAttribute('data-adv-view')===view);});if(view==='management')renderView();else loadRecords();};

  async function loadRecords(){if(loading)return;loading=true;lastLoadError='';renderView();try{if(currentView==='dashboard'){if(!apiReady('_advisoryGetPublic'))throw new Error('Record request data service is unavailable.');records=await window._advisoryGetPublic();}else if(isAdmin()){if(!apiReady('_advisoryGetAll'))throw new Error('Record request data service is unavailable.');records=await window._advisoryGetAll();}else{if(!apiReady('_advisoryGetMine'))throw new Error('Record request data service is unavailable.');records=await window._advisoryGetMine();}records=(records||[]).filter(isRelevantRecord);}catch(e){lastLoadError=String(e&&e.message||e);records=[];}loading=false;renderView();if(currentView==='requests'&&!isAdmin())showRatingNotification();}
  window._advReload=function(){loadRecords();};
  function renderView(){var h=host();if(!h)return;if(loading){h.innerHTML='<div class="adv-loading">Loading Review & Development Center…</div>';return;}var prefix=lastLoadError?'<div class="adv-error">'+esc(lastLoadError)+'</div>':'';if(currentView==='dashboard')h.innerHTML=prefix+dashboardHtml();else if(currentView==='requests')h.innerHTML=prefix+requestsHtml();else h.innerHTML=managementHtml();}

  function scopedPublicRecords(){var all=records.filter(isRelevantRecord);return isAdmin()?all:all.filter(function(r){return r.departmentKey===userDepartmentKey();});}
  function filterRecords(base){var q=dashboardSearch.toLowerCase().trim();return base.filter(function(r){if(departmentFilter&&r.departmentKey!==departmentFilter)return false;if(dashboardStatus&&r.status!==dashboardStatus)return false;var t=normalizedType(r);if(dashboardFilter==='edit_review'&&t!=='edit_review')return false;if(dashboardFilter==='new'&&t!=='new')return false;if(dashboardFilter==='approved'&&!approved(r))return false;if(q&&[r.code,typeLabel(r),r.category,relatedText(r),departmentName(r.departmentKey),statusLabel(r.status)].join(' ').toLowerCase().indexOf(q)<0)return false;return true;});}
  function metric(label,value,sub,filter,tone){var icons={info:'▦',good:'✓',warn:'△',purple:'◇'};return'<div class="grc-metric-card adv-metric-card '+tone+' clickable '+(dashboardFilter===filter?'is-active':'')+'" onclick="window._advDashboardFilter(\''+filter+'\')" tabindex="0" role="button"><div class="grc-metric-top"><span class="grc-metric-icon">'+(icons[tone]||'▦')+'</span></div><div class="grc-metric-value">'+value+'</div><div class="grc-metric-label">'+label+'</div><div class="grc-metric-foot"><span class="grc-metric-sub">'+sub+'</span><span class="grc-metric-arrow">›</span></div></div>';}
  function dashboardHtml(){
    var base=scopedPublicRecords(),editCount=base.filter(function(r){return normalizedType(r)==='edit_review';}).length,newCount=base.filter(function(r){return normalizedType(r)==='new';}).length,approvedCount=base.filter(approved).length,rate=base.length?Math.round(approvedCount/base.length*100):0,displayed=filterRecords(base);
    return'<section class="adv-view is-active"><div class="grc-section-head"><div><div class="grc-section-title">Review & Development Dashboard</div><div class="grc-section-sub">'+(isAdmin()?'All FMS departments · '+PLATFORM_LABELS[currentPlatform]:'Department scope: '+esc(departmentName(userDepartmentKey()))+' · '+PLATFORM_LABELS[currentPlatform])+'</div></div><span class="grc-section-badge">No personal data</span></div><div class="adv-metric-grid">'+
      metric('Total Requests',base.length,'All submitted requests','all','info')+metric('Existing Item Review & Update',editCount,base.length?Math.round(editCount/base.length*100)+'% of total':'0% of total','edit_review','purple')+metric('New Item Requests',newCount,base.length?Math.round(newCount/base.length*100)+'% of total':'0% of total','new','info')+metric('Approvals',approvedCount,'Completed or closed requests','approved','good')+metric('Approval Rate',rate+'%',approvedCount+' approved of '+base.length+' requests','approved','good')+
      '</div><div class="adv-grid-2" style="margin-top:14px">'+departmentBars(base)+statusSummary(base)+'</div>'+registerHtml(displayed,base.length)+'</section>';
  }
  function departmentBars(base){var c={};base.forEach(function(r){var k=r.departmentKey||'other';c[k]=(c[k]||0)+1;});var max=Math.max.apply(null,[1].concat(Object.keys(c).map(function(k){return c[k];})));return'<div class="adv-card"><h3 class="adv-card-title">Requests by Department</h3><div class="adv-dept-bars">'+(Object.keys(c).sort(function(a,b){return c[b]-c[a];}).map(function(k){return'<div class="adv-dept-bar '+(departmentFilter===k?'is-active':'')+'" onclick="window._advDepartmentFilter(\''+esc(k)+'\')"><span>'+esc(departmentName(k))+'</span><div class="adv-dept-track"><i style="width:'+Math.round(c[k]/max*100)+'%"></i></div><b>'+c[k]+'</b></div>';}).join('')||'<div class="adv-empty">No records available.</div>')+'</div></div>';}
  function statusSummary(base){function n(s){return base.filter(function(r){return r.status===s;}).length;}return'<div class="adv-card"><h3 class="adv-card-title">Current Status Distribution</h3><div class="adv-status-summary"><div class="adv-status-tile"><b>'+n('under_review')+'</b><span>Under Review</span></div><div class="adv-status-tile"><b>'+n('in_progress')+'</b><span>In Progress</span></div><div class="adv-status-tile"><b>'+n('awaiting_requester_information')+'</b><span>Awaiting Information</span></div><div class="adv-status-tile"><b>'+n('responded')+'</b><span>Responded</span></div><div class="adv-status-tile"><b>'+n('completed')+'</b><span>Completed</span></div><div class="adv-status-tile"><b>'+n('closed')+'</b><span>Closed</span></div></div></div>';}
  function filterTitle(){return{all:'All Requests',edit_review:'Existing Item Review & Update',new:'New Item Requests',approved:'Approvals'}[dashboardFilter]||'All Requests';}
  function registerHtml(list,total){var dept=isAdmin()?'<select onchange="window._advDepartmentFilter(this.value,true)"><option value="">All Departments</option>'+Object.keys(DEPARTMENTS).filter(function(k){return k!=='division';}).map(function(k){return'<option value="'+k+'" '+(departmentFilter===k?'selected':'')+'>'+DEPARTMENTS[k].name+'</option>';}).join('')+'</select>':'';return'<div class="adv-card" style="margin-top:14px"><div class="adv-register-toolbar"><div><h3>Request & Review Register</h3><p>Each row contains non-personal request data only.</p></div><div class="adv-filter-note">Showing <b>'+list.length+'</b> of <b>'+total+'</b> requests · '+esc(filterTitle())+'</div></div><div class="adv-filters"><input value="'+esc(dashboardSearch)+'" placeholder="Search by code, item type or related record" oninput="window._advSetDashboardFilter(\'search\',this.value)">'+dept+'<select onchange="window._advSetDashboardFilter(\'status\',this.value)"><option value="">All Statuses</option>'+Object.keys(STATUS_LABELS).map(function(k){return'<option value="'+k+'" '+(dashboardStatus===k?'selected':'')+'>'+STATUS_LABELS[k]+'</option>';}).join('')+'</select><button class="adv-btn ghost" onclick="window._advResetFilters()">Reset</button></div>'+publicTable(list)+'</div>';}
  function relatedText(r){var a=Array.isArray(r.relatedItems)?r.relatedItems:[],v=a.map(function(x){return x.code?x.code+' — '+x.name:(x.name||x.label||'');}).filter(Boolean);if(r.relatedNewText)v.push('New: '+r.relatedNewText);return v.join('; ')||'—';}
  function publicTable(list){return'<div class="adv-table-wrap"><table class="adv-table"><thead><tr><th>Request Code</th><th>Request Type</th><th>Item Type</th><th>Related Record(s)</th><th>Department</th><th>Priority</th><th>Request Date</th><th>Status</th><th>First Response</th><th>Response Duration</th><th>Rating</th></tr></thead><tbody>'+(list.length?list.map(function(r){return'<tr><td class="adv-code">'+esc(r.code||r.id)+'</td><td>'+esc(typeLabel(r))+'</td><td>'+esc(r.category||r.relatedType||'—')+'</td><td>'+esc(relatedText(r))+'</td><td>'+esc(departmentName(r.departmentKey))+'</td><td>'+esc(r.priority||'Normal')+'</td><td>'+formatDate(r.createdAt,false)+'</td><td>'+statusBadge(r.status)+'</td><td>'+formatDate(r.firstRespondedAt||r.respondedAt,true)+'</td><td>'+durationText(responseMinutes(r))+'</td><td>'+stars(r.rating)+'</td></tr>';}).join(''):'<tr><td colspan="11"><div class="adv-empty">No requests match the selected filters.</div></td></tr>')+'</tbody></table></div>';}
  window._advDashboardFilter=function(f){dashboardFilter=f;renderView();setTimeout(function(){var r=root(),t=r&&r.querySelector('.adv-table-wrap');if(t)t.scrollIntoView({behavior:'smooth',block:'start'});},30);};
  window._advDepartmentFilter=function(k,fromSelect){departmentFilter=fromSelect?k:(departmentFilter===k?'':k);renderView();};
  window._advSetDashboardFilter=function(k,v){if(k==='search')dashboardSearch=String(v||'');if(k==='status')dashboardStatus=String(v||'');renderView();};
  window._advResetFilters=function(){dashboardFilter='all';departmentFilter='';dashboardSearch='';dashboardStatus='';renderView();};

  function requestsHtml(){return'<section class="adv-view is-active"><div class="grc-section-head"><div><div class="grc-section-title">Review & Development Requests</div><div class="grc-section-sub">'+(isAdmin()?'Review and respond to '+PLATFORM_LABELS[currentPlatform]+' requests.':'Submit an Existing Item Review & Update request or a New Item Request.')+'</div></div><button class="grc-primary-btn" onclick="window._advOpenGuidanceRequest()">＋ Submit Request</button></div>'+(isAdmin()?adminRequestsHtml():ownRequestsHtml())+'</section>';}
  function ownRequestsHtml(){var list=records.slice().sort(function(a,b){return timeMs(b.createdAt)-timeMs(a.createdAt);});return'<div class="adv-action-grid adv-action-grid-single"><button class="adv-action-card" onclick="window._advOpenGuidanceRequest()"><strong>✦ Submit a Request</strong><span>Choose Existing Item Review & Update for an item already listed, or New Item Request for an item not yet listed.</span></button></div><div class="adv-card"><div class="adv-register-toolbar"><div><h3>Submitted Review & Development Requests</h3><p>Your '+PLATFORM_LABELS[currentPlatform]+' requests only.</p></div><button class="adv-btn ghost" onclick="window._advReload()">Refresh</button></div><div class="adv-table-wrap"><table class="adv-table" style="min-width:900px"><thead><tr><th>Request Code</th><th>Request Type</th><th>Item Type</th><th>Related Record(s)</th><th>Submitted</th><th>Status</th><th>Last Update</th><th>Rating</th><th></th></tr></thead><tbody>'+(list.length?list.map(function(r){return'<tr><td class="adv-code">'+esc(r.code||r.id)+'</td><td>'+esc(typeLabel(r))+'</td><td>'+esc(r.category||r.relatedType||'—')+'</td><td>'+esc(relatedText(r))+'</td><td>'+formatDate(r.createdAt,true)+'</td><td>'+statusBadge(r.status)+'</td><td>'+formatDate(r.updatedAt||r.respondedAt||r.createdAt,true)+'</td><td>'+stars(r.rating)+'</td><td><button class="adv-btn secondary" onclick="window._advOpenRequest(\''+esc(r.id)+'\')">Open</button></td></tr>';}).join(''):'<tr><td colspan="9"><div class="adv-empty">No requests have been submitted yet.</div></td></tr>')+'</tbody></table></div></div>';}
  function filteredAdminRecords(){var q=adminSearch.toLowerCase().trim();return records.filter(function(r){if(adminStatus&&r.status!==adminStatus)return false;if(adminDepartment&&r.departmentKey!==adminDepartment)return false;if(q&&[r.code,r.userName,r.userEmail,r.category,relatedText(r),departmentName(r.departmentKey),statusLabel(r.status)].join(' ').toLowerCase().indexOf(q)<0)return false;return true;}).sort(function(a,b){return timeMs(b.createdAt)-timeMs(a.createdAt);});}
  function adminRequestsHtml(){var list=filteredAdminRecords();return'<div class="adv-personal-note"><strong>Authorized view:</strong> Requester name and email are available to Admin and Super Admin for response and follow-up.</div><div class="adv-filters"><input value="'+esc(adminSearch)+'" placeholder="Search by code, requester, email, department, item type or record" oninput="window._advSetAdminFilter(\'search\',this.value)"><select onchange="window._advSetAdminFilter(\'status\',this.value)"><option value="">All Statuses</option>'+Object.keys(STATUS_LABELS).map(function(k){return'<option value="'+k+'" '+(adminStatus===k?'selected':'')+'>'+STATUS_LABELS[k]+'</option>';}).join('')+'</select><select onchange="window._advSetAdminFilter(\'department\',this.value)"><option value="">All Departments</option>'+Object.keys(DEPARTMENTS).filter(function(k){return k!=='division';}).map(function(k){return'<option value="'+k+'" '+(adminDepartment===k?'selected':'')+'>'+DEPARTMENTS[k].name+'</option>';}).join('')+'</select></div><div class="adv-table-wrap"><table class="adv-table" style="min-width:1300px"><thead><tr><th>Request Code</th><th>Requester</th><th>Email</th><th>Department</th><th>Request Type</th><th>Item Type</th><th>Related Record(s)</th><th>Priority</th><th>Status</th><th>Submitted</th><th>First Response</th><th></th></tr></thead><tbody>'+(list.length?list.map(function(r){return'<tr><td class="adv-code">'+esc(r.code||r.id)+'</td><td>'+esc(r.userName||'—')+'</td><td>'+esc(r.userEmail||'—')+'</td><td>'+esc(departmentName(r.departmentKey))+'</td><td>'+esc(typeLabel(r))+'</td><td>'+esc(r.category||r.relatedType||'—')+'</td><td>'+esc(relatedText(r))+'</td><td>'+esc(r.priority||'Normal')+'</td><td>'+statusBadge(r.status)+'</td><td>'+formatDate(r.createdAt,true)+'</td><td>'+formatDate(r.firstRespondedAt||r.respondedAt,true)+'</td><td><button class="adv-btn primary" onclick="window._advOpenRequest(\''+esc(r.id)+'\')">Open & Respond</button></td></tr>';}).join(''):'<tr><td colspan="12"><div class="adv-empty">No requests found.</div></td></tr>')+'</tbody></table></div>';}
  window._advSetAdminFilter=function(k,v){if(k==='search')adminSearch=String(v||'');if(k==='status')adminStatus=String(v||'');if(k==='department')adminDepartment=String(v||'');renderView();};

  function workflowStep(n,t,d){return'<div class="adv-workflow-step"><b>'+n+'</b><div><strong>'+t+'</strong><span>'+d+'</span></div></div>';}
  function managementHtml(){var types=ITEM_TYPES[currentPlatform];return'<section class="adv-view is-active"><div class="grc-section-head"><div><div class="grc-section-title">Review & Development Center Management</div><div class="grc-section-sub">Approved request types, item scopes and action-driven workflow.</div></div><span class="grc-section-badge">SUPER ADMIN</span></div><div class="adv-management-grid"><div class="adv-card"><h3 class="adv-card-title">Request Types</h3><span class="adv-chip">Existing Item Review & Update</span><span class="adv-chip">New Item Request</span></div><div class="adv-card"><h3 class="adv-card-title">Available Item Types</h3>'+types.map(function(x){return'<span class="adv-chip">'+esc(x.label)+'</span>';}).join('')+'</div><div class="adv-card"><h3 class="adv-card-title">Automatic Status Workflow</h3><div class="adv-workflow">'+workflowStep(1,'Under Review','Assigned automatically when submitted.')+workflowStep(2,'Awaiting Information from Requester','Applied when Admin requests more information.')+workflowStep(3,'In Progress','Applied when the requester sends clarification.')+workflowStep(4,'Responded','Applied when Admin sends the response.')+workflowStep(5,'Completed','Applied when the requester confirms completion.')+workflowStep(6,'Closed','Applied by Admin after completion.')+'</div></div><div class="adv-card"><h3 class="adv-card-title">Department-Based Records</h3><p style="font-size:9px;color:#718692;line-height:1.7">Existing Item Review & Update displays existing records from the requester\'s department only and allows multiple selection. New Item Request requires the requested item type and proposed name.</p></div></div></section>';}

  function performanceOptions(){var dept=userDepartmentKey(),items=[];try{var all=typeof window.allK==='function'?window.allK():(typeof allK==='function'?allK():[]);items=(all||[]).filter(function(k){var kd=String(k.dept||k.department||'').toLowerCase();return kd===dept||(dept==='projects'&&kd.indexOf('project')>=0)||(dept==='governance'&&(kd.indexOf('govern')>=0||kd.indexOf('performance')>=0));}).map(function(k){return{type:'kpi',id:String(k.id||k.code||''),code:String(k.id||k.code||''),name:String(k.nameEn||k.name||k.title||'KPI')};});}catch(_){}return{kpis:items};}
  function grcOptions(){try{if(typeof window._grcGetAdvisoryOptions==='function')return window._grcGetAdvisoryOptions(userDepartmentKey())||{};}catch(_){}return{};}
  function itemDef(value){return(ITEM_TYPES[currentPlatform]||[]).find(function(x){return x.value===value;})||null;}
  function optionsFor(def){var data=currentPlatform==='performance'?performanceOptions():grcOptions();return def&&Array.isArray(data[def.key])?data[def.key]:[];}

  window._advOpenGuidanceRequest=function(){closeModal();document.body.classList.add('adv-modal-open');var dept=userDepartmentKey(),ov=document.createElement('div');ov.id='advModal';ov.className='adv-modal-backdrop';ov.innerHTML='<div class="adv-modal"><div class="adv-modal-head"><div><h2>New Review & Development Request</h2><p>'+PLATFORM_LABELS[currentPlatform]+' · '+esc(departmentName(dept))+'</p></div><button class="adv-modal-close" onclick="window._advCloseModal()">×</button></div><div class="adv-modal-body"><div class="adv-form"><div class="adv-field"><label>Request Type *</label><select id="advRequestType" onchange="window._advTypeChanged()"><option value="">Select request type</option><option value="edit_review">Existing Item Review & Update</option><option value="new">New Item Request</option></select></div><div class="adv-field" id="advItemTypeField" style="display:none"><label>Item Type *</label><select id="advItemType" onchange="window._advItemTypeChanged()"><option value="">Select item type</option></select></div><div class="adv-field full" id="advRelatedField" style="display:none"></div><div class="adv-field full"><label>Request Title *</label><input id="advTitle" placeholder="Enter a concise request title"></div><div class="adv-field full"><label>Request Details *</label><textarea id="advDetails" placeholder="Describe the review, proposed update, or new item requirement"></textarea></div><div class="adv-field"><label>Priority</label><select id="advPriority"><option>Low</option><option selected>Normal</option><option>High</option></select></div><div class="adv-field full"><label>Attachment (optional)</label><input id="advAttachment" type="file"><small>Maximum file size: 5 MB.</small></div></div></div><div class="adv-modal-actions"><button class="adv-btn ghost" onclick="window._advCloseModal()">Cancel</button><button class="adv-btn primary" onclick="window._advSubmitConsultation()">Submit Request</button></div></div>';document.body.appendChild(ov);ov.addEventListener('click',function(e){if(e.target===ov)closeModal();});};
  window._advTypeChanged=function(){var type=String((document.getElementById('advRequestType')||{}).value||''),field=document.getElementById('advItemTypeField'),sel=document.getElementById('advItemType'),related=document.getElementById('advRelatedField');if(!field||!sel)return;if(!type){field.style.display='none';sel.innerHTML='<option value="">Select item type</option>';if(related){related.style.display='none';related.innerHTML='';}return;}field.style.display='flex';sel.innerHTML='<option value="">Select item type</option>'+(ITEM_TYPES[currentPlatform]||[]).map(function(x){return'<option value="'+x.value+'">'+esc(x.label)+'</option>';}).join('');if(related){related.style.display='none';related.innerHTML='';}};
  window._advItemTypeChanged=function(){var type=String((document.getElementById('advRequestType')||{}).value||''),value=String((document.getElementById('advItemType')||{}).value||''),def=itemDef(value),related=document.getElementById('advRelatedField');if(!related)return;if(!type||!def){related.style.display='none';related.innerHTML='';return;}related.style.display='flex';if(type==='new'){related.innerHTML='<label>Proposed '+esc(def.label)+' Name(s) *</label><textarea id="advRelatedNewText" placeholder="Enter the proposed name. Use a new line for more than one item."></textarea><input type="hidden" id="advRelatedType" value="'+esc(def.label)+'">';return;}var options=optionsFor(def);related.innerHTML='<label>Select Existing '+esc(def.label)+' Record(s) <span style="font-weight:600;color:#80929c">(multiple selection allowed)</span></label><div class="adv-related-list">'+(options.length?options.map(function(x){var val=encodeURIComponent(JSON.stringify(x));return'<label class="adv-related-option"><input type="checkbox" name="advRelatedItem" value="'+esc(val)+'"><span><b>'+esc(x.code||x.id||'')+'</b>'+esc(x.name||x.label||'')+'</span></label>';}).join(''):'<div class="adv-empty" style="padding:14px">No existing records are available for your department.</div>')+'</div><input type="hidden" id="advRelatedType" value="'+esc(def.label)+'">';};
  function selectedRelatedItems(){return Array.prototype.map.call(document.querySelectorAll('input[name="advRelatedItem"]:checked'),function(x){try{return JSON.parse(decodeURIComponent(x.value));}catch(_){return null;}}).filter(Boolean);}
  window._advSubmitConsultation=async function(){var type=String((document.getElementById('advRequestType')||{}).value||''),itemValue=String((document.getElementById('advItemType')||{}).value||''),def=itemDef(itemValue),title=String((document.getElementById('advTitle')||{}).value||'').trim(),details=String((document.getElementById('advDetails')||{}).value||'').trim(),priority=String((document.getElementById('advPriority')||{}).value||'Normal'),file=(document.getElementById('advAttachment')||{}).files&&document.getElementById('advAttachment').files[0],relatedItems=selectedRelatedItems(),relatedNewText=String((document.getElementById('advRelatedNewText')||{}).value||'').trim();if(!type||!def||!title||!details){toast('Complete the request type, item type, title and details.');return;}if(type==='edit_review'&&!relatedItems.length){toast('Select at least one existing record.');return;}if(type==='new'&&!relatedNewText){toast('Enter the proposed new item name.');return;}if(file&&file.size>5*1024*1024){toast('The attachment must be 5 MB or smaller.');return;}if(!apiReady('_advisorySubmit')){toast('Record request service is unavailable.');return;}var dept=userDepartmentKey();try{var result=await window._advisorySubmit({platform:currentPlatform,departmentKey:dept,departmentCode:departmentCode(dept),priority:priority,serviceType:'record_request_review',requestType:type,requestTypeLabel:TYPE_LABELS[type],category:def.label,title:title,details:details,relatedType:def.label,relatedItems:relatedItems,relatedNewText:type==='new'?relatedNewText:''},file||null);audit('REVIEW_DEVELOPMENT_REQUEST_SUBMIT','Submitted '+currentPlatform+' request '+(result&&result.code||''));closeModal();currentView='requests';await loadRecords();toast('Request submitted successfully: '+(result&&result.code||''));}catch(e){toast(String(e&&e.message||e));}};


  window._advOpenPlatformRequest=function(platform){
    platform=platform==='performance'?'performance':'grc';
    if(platform==='grc'&&typeof window._grcSwitch==='function')window._grcSwitch('advisory');
    if(platform==='performance'&&typeof window.switchPage==='function')window.switchPage('advisory');
    setTimeout(function(){
      if(platform==='grc'){currentPlatform='grc';currentRootId='advRootGrc';}
      else{currentPlatform='performance';currentRootId='advRootPerformance';}
      window._advOpenGuidanceRequest();
    },180);
  };
  window._advOpenPlatformRequests=function(platform){
    platform=platform==='performance'?'performance':'grc';
    if(platform==='grc'&&typeof window._grcSwitch==='function')window._grcSwitch('advisory');
    if(platform==='performance'&&typeof window.switchPage==='function')window.switchPage('advisory');
    setTimeout(function(){
      currentPlatform=platform;currentRootId=platform==='grc'?'advRootGrc':'advRootPerformance';
      currentView='requests';
      var r=root();if(r)r.querySelectorAll('.adv-module-card').forEach(function(x){x.classList.toggle('is-active',x.getAttribute('data-adv-view')==='requests');});
      loadRecords();
    },220);
  };

  window._advOpenRequest=async function(id){if(!apiReady('_advisoryGetOne'))return;try{selectedRequest=await window._advisoryGetOne(id);if(recordPlatform(selectedRequest)!==currentPlatform)throw new Error('This request belongs to another platform.');showRequestModal(selectedRequest);}catch(e){toast(String(e&&e.message||e));}};
  function detail(l,v){return'<div class="adv-detail-item"><span>'+esc(l)+'</span><b>'+esc(v)+'</b></div>';}
  function messageHtml(m){return'<div class="adv-message '+(m.senderRole==='admin'||m.senderRole==='super_admin'?'admin':'requester')+'"><div class="adv-message-head"><strong>'+esc(m.senderName||m.senderRole||'User')+'</strong><span>'+formatDate(m.createdAt,true)+'</span></div><div class="adv-message-body">'+esc(m.text||'')+'</div>'+attachmentHtml(m.attachments||[])+'</div>';}
  function attachmentHtml(list){return(list||[]).map(function(a){return'<button class="adv-attachment" onclick="window._advDownloadAttachment(\''+esc(selectedRequest&&selectedRequest.id||'')+'\',\''+esc(a.id)+'\',\''+esc(a.name||'attachment')+'\',\''+esc(a.type||'application/octet-stream')+'\','+Number(a.chunkCount||0)+')">▣ '+esc(a.name||'Attachment')+'</button>';}).join('');}
  function requestDetails(r){var personal=isAdmin()?'<div class="adv-personal-note"><strong>Requester information:</strong> '+esc(r.userName||'—')+' · '+esc(r.userEmail||'—')+' · '+esc(departmentName(r.departmentKey))+'</div>':'';var meta='<div class="adv-detail-grid">'+detail('Request Type',typeLabel(r))+detail('Item Type',r.category||r.relatedType||'—')+detail('Priority',r.priority||'Normal')+detail('Created',formatDate(r.createdAt,true))+detail('First Response',formatDate(r.firstRespondedAt||r.respondedAt,true))+detail('Response Duration',durationText(responseMinutes(r)))+'</div>';var body='<div class="adv-card" style="margin-bottom:12px"><h3 class="adv-card-title">'+esc(r.title||'Request Details')+'</h3><div style="font-size:9.5px;line-height:1.7;color:#3b5865;white-space:pre-wrap">'+esc(r.details||'—')+'</div><div class="adv-detail-grid" style="margin-top:12px">'+detail('Related Record(s)',relatedText(r))+detail('Status',statusLabel(r.status))+'</div></div>';var attachments=attachmentHtml(r.attachments||[]),conversation='<div class="adv-card"><h3 class="adv-card-title">Responses & Clarifications</h3>'+((r.messages||[]).length?(r.messages||[]).map(messageHtml).join(''):'<div class="adv-empty">No responses or clarifications yet.</div>')+'</div>';return personal+meta+body+(attachments?'<div class="adv-card" style="margin-bottom:12px"><h3 class="adv-card-title">Attachments</h3>'+attachments+'</div>':'')+conversation;}
  function showRequestModal(r){closeModal(false);document.body.classList.add('adv-modal-open');selectedRequest=r;var ov=document.createElement('div');ov.id='advModal';ov.className='adv-modal-backdrop';ov.innerHTML='<div class="adv-modal adv-modal-wide"><div class="adv-modal-head"><div><h2>'+esc(r.code||'Review & Development Request')+'</h2><p>'+esc(PLATFORM_LABELS[recordPlatform(r)]+' · '+typeLabel(r)+' · '+statusLabel(r.status))+'</p></div><button class="adv-modal-close" onclick="window._advCloseModal()">×</button></div><div class="adv-modal-body">'+requestDetails(r)+(isAdmin()?adminActions(r):requesterActions(r))+'</div></div>';document.body.appendChild(ov);ov.addEventListener('click',function(e){if(e.target===ov)closeModal();});}
  window._advDownloadAttachment=async function(requestId,attachmentId,name,type,count){if(!apiReady('_advisoryDownloadAttachment'))return toast('Attachment service is unavailable.');try{var blob=await window._advisoryDownloadAttachment(requestId,attachmentId,type,count),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name||'attachment';document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},1000);}catch(e){toast(String(e&&e.message||e));}};
  function adminActions(r){var canClose=r.status==='completed';return'<div class="adv-card" style="margin-top:12px"><h3 class="adv-card-title">Admin Action</h3><div class="adv-form"><div class="adv-field full"><label>Response / Recommendation</label><textarea id="advAdminReply" placeholder="Write the response shown to the requester"></textarea></div><div class="adv-field full"><label>Attachment (optional)</label><input id="advAdminAttachment" type="file"></div><div class="adv-field full"><div class="adv-modal-actions" style="justify-content:flex-start"><button class="adv-btn primary" onclick="window._advAdminAction(\'respond\')">Send Response</button><button class="adv-btn warn" onclick="window._advAdminAction(\'request_info\')">Request More Information</button>'+(canClose?'<button class="adv-btn good" onclick="window._advAdminAction(\'close\')">Close Completed Request</button>':'')+'<select id="advExceptionalAction" style="padding:8px 9px;border:1px solid #d7e2e7;border-radius:9px;font-size:9px"><option value="">Exceptional Action</option><option value="duplicate">Mark as Duplicate</option><option value="out_of_scope">Mark as Out of Scope</option><option value="knowledge_guide">Direct to Knowledge Guide</option></select><button class="adv-btn ghost" onclick="window._advApplyExceptional()">Apply</button></div></div></div></div>';}
  window._advAdminAction=async function(action){if(!selectedRequest||!apiReady('_advisoryAdminAction'))return;var reply=String((document.getElementById('advAdminReply')||{}).value||'').trim(),file=(document.getElementById('advAdminAttachment')||{}).files&&document.getElementById('advAdminAttachment').files[0];if((action==='respond'||action==='request_info')&&!reply)return toast('Enter a response or information request first.');try{await window._advisoryAdminAction(selectedRequest.id,action,{text:reply},file||null);audit('REVIEW_DEVELOPMENT_ADMIN_ACTION',action+' on '+selectedRequest.code);closeModal();await loadRecords();toast(action==='close'?'Request closed. The requester will be prompted to rate the service.':'Request updated successfully.');}catch(e){toast(String(e&&e.message||e));}};
  window._advApplyExceptional=function(){var v=String((document.getElementById('advExceptionalAction')||{}).value||'');if(!v)return toast('Select an exceptional action.');window._advAdminAction(v);};
  function requesterActions(r){var h='';if(r.status==='awaiting_requester_information')h+='<div class="adv-card" style="margin-top:12px"><h3 class="adv-card-title">Provide Additional Information</h3><div class="adv-form"><div class="adv-field full"><label>Clarification *</label><textarea id="advClarification"></textarea></div><div class="adv-field full"><label>Attachment (optional)</label><input id="advClarificationFile" type="file"></div><div class="adv-field full"><button class="adv-btn primary" onclick="window._advSendClarification()">Send Clarification</button></div></div></div>';if(r.status==='responded')h+='<div class="adv-card" style="margin-top:12px"><h3 class="adv-card-title">Confirm Completion</h3><button class="adv-btn good" onclick="window._advConfirmComplete()">Confirm Completed</button></div>';if(['under_review','in_progress','awaiting_requester_information'].indexOf(r.status)>=0)h+='<div style="margin-top:12px;text-align:right"><button class="adv-btn danger" onclick="window._advCancelRequest()">Cancel Request</button></div>';if(r.status==='closed'&&!Number(r.rating))h+='<div class="adv-card" style="margin-top:12px"><h3 class="adv-card-title">Rate Your Experience</h3><div class="adv-stars">'+[1,2,3,4,5].map(function(n){return'<button class="adv-star" onclick="window._advRate('+n+')">★</button>';}).join('')+'</div></div>';return h;}
  window._advSendClarification=async function(){var text=String((document.getElementById('advClarification')||{}).value||'').trim(),file=(document.getElementById('advClarificationFile')||{}).files&&document.getElementById('advClarificationFile').files[0];if(!text)return toast('Enter the clarification first.');try{await window._advisoryRequesterAction(selectedRequest.id,'clarify',{text:text},file||null);closeModal();await loadRecords();toast('Clarification sent.');}catch(e){toast(String(e&&e.message||e));}};
  window._advConfirmComplete=async function(){try{await window._advisoryRequesterAction(selectedRequest.id,'complete',{},null);closeModal();await loadRecords();toast('Request marked as Completed.');}catch(e){toast(String(e&&e.message||e));}};
  window._advCancelRequest=async function(){if(!window.confirm('Cancel this request?'))return;try{await window._advisoryRequesterAction(selectedRequest.id,'cancel',{},null);closeModal();await loadRecords();toast('Request cancelled.');}catch(e){toast(String(e&&e.message||e));}};
  window._advRate=async function(rating){try{await window._advisoryRate(selectedRequest.id,rating);closeModal();await loadRecords();toast('Thank you. Your rating was saved.');}catch(e){toast(String(e&&e.message||e));}};
  function showRatingNotification(){if(currentView!=='requests')return;var r=records.find(function(x){return x.status==='closed'&&!Number(x.rating);});if(!r)return;var key='qumc_adv_rating_notice_'+r.id;if(sessionStorage.getItem(key))return;sessionStorage.setItem(key,'1');setTimeout(function(){toast('Request '+(r.code||'')+' is closed. Please rate your experience.');},400);}
  function closeModal(clear){var m=document.getElementById('advModal');if(m)m.remove();document.body.classList.remove('adv-modal-open');if(clear!==false)selectedRequest=null;}
  window._advCloseModal=function(){closeModal();};
})();
