/* ======================================================================
   QUMC GRC — Excel / Report / Page Export
   Build: 2026-07-23 v1
   ====================================================================== */
(function(){
  'use strict';
  var PAGE_LABELS={executive:'Executive Command',governance:'Governance',risk:'Risk Management',register:'Registers',compliance:'Compliance',actions:'Action Plans',documents:'Documents & Records',reports:'Reports',manuals:'FMS Manual',advisory:'Advisory Center'};
  var DEPTS=[['safety','Safety'],['maintenance','Maintenance'],['housekeeping','Housekeeping'],['laundry','Laundry'],['projects','Project Management'],['governance','Governance & Performance']];
  function esc(v){return String(v==null?'':v).replace(/[&<>'"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c];});}
  function snap(){return typeof window._grcGetExportSnapshot==='function'?(window._grcGetExportSnapshot()||{}):{};}
  function modules(){return typeof window._grcGetModules==='function'?window._grcGetModules():Object.keys(PAGE_LABELS).map(function(id){return{id:id,label:PAGE_LABELS[id]};});}
  function closeOverlay(){var x=document.getElementById('grcExportOverlay');if(x)x.remove();document.body.classList.remove('grc-export-open');}
  function overlay(title,sub,body,confirmLabel,confirmFn){closeOverlay();document.body.classList.add('grc-export-open');var ov=document.createElement('div');ov.id='grcExportOverlay';ov.className='grc-export-overlay';ov.innerHTML='<div class="grc-export-dialog"><div class="grc-export-dialog-head"><div><h2>'+esc(title)+'</h2><p>'+esc(sub||'')+'</p></div><button type="button" onclick="window._grcCloseExportDialog()">×</button></div><div class="grc-export-dialog-body">'+body+'<div class="grc-export-actions-row"><button type="button" class="grc-export-cancel" onclick="window._grcCloseExportDialog()">Cancel</button><button type="button" class="grc-export-confirm" onclick="'+confirmFn+'">'+esc(confirmLabel)+'</button></div></div></div>';document.body.appendChild(ov);ov.addEventListener('click',function(e){if(e.target===ov)closeOverlay();});}
  window._grcCloseExportDialog=closeOverlay;
  function checked(name){return Array.prototype.map.call(document.querySelectorAll('input[name="'+name+'"]:checked'),function(x){return x.value;});}
  function deptMatch(r,depts){if(!depts.length)return true;r=r||{};var rd=String(r.department||r.dept||'').toLowerCase(),hay=[r.id,r.code,r.name,r.nameEn,r.title,r.titleEn,r.riskIdentified].join(' ').toUpperCase();return depts.some(function(d){if(d==='governance')return rd==='governance'||rd==='division'||rd==='governancedept';if(d==='laundry')return rd==='laundry'||/\bLUND|LAUNDRY/.test(hay);if(d==='housekeeping')return rd==='housekeeping'&&!/\bLUND|LAUNDRY/.test(hay);return rd===d;});}
  function recordKey(r){return String(r&&r.id||r&&r.code||'');}
  function recordLabel(r){return[String(r&&r.code||r&&r.id||''),String(r&&r.nameEn||r&&r.name||r&&r.titleEn||r&&r.title||r&&r.riskIdentified||'')].filter(Boolean).join(' — ');}
  function recordsHtml(type,rows){return'<div class="grc-export-section"><h3>Specific '+type+' <span style="font-weight:500;color:#78909A">(optional — leave blank to include all matching records)</span></h3><div class="grc-export-record-list">'+(rows.length?rows.map(function(r){return'<label class="grc-export-check"><input type="checkbox" name="grcSpecific'+type+'" value="'+esc(recordKey(r))+'"><span>'+esc(recordLabel(r))+'</span></label>';}).join(''):'<div style="font-size:9px;color:#78909A;padding:10px">No records available for the selected departments.</div>')+'</div></div>';}
  function refreshSpecificLists(){var box=document.getElementById('grcSpecificRecords');if(!box)return;var data=snap(),depts=checked('grcExcelDept');var pol=(data.policies||[]).filter(function(r){return deptMatch(r,depts);}),forms=(data.forms||[]).filter(function(r){return deptMatch(r,depts);});box.innerHTML=recordsHtml('Policies',pol)+recordsHtml('Forms',forms);}
  window._grcRefreshSpecificLists=refreshSpecificLists;
  window._grcOpenExcelSelector=function(){
    var pageChecks=modules().map(function(m){return'<label class="grc-export-check"><input type="checkbox" name="grcExcelPage" value="'+esc(m.id)+'" '+(['executive','governance','risk','register'].indexOf(m.id)>=0?'checked':'')+'><span>'+esc(PAGE_LABELS[m.id]||m.label)+'</span></label>';}).join('');
    var deptChecks=DEPTS.map(function(d){return'<label class="grc-export-check"><input type="checkbox" name="grcExcelDept" value="'+d[0]+'" checked onchange="window._grcRefreshSpecificLists()"><span>'+d[1]+'</span></label>';}).join('');
    overlay('GRC Excel Export','Choose departments, platform pages and optional specific policies or forms. Each selected page will be created as a separate worksheet.','<div class="grc-export-section"><h3>Departments</h3><div class="grc-export-check-grid">'+deptChecks+'</div></div><div class="grc-export-section"><h3>Worksheets / Platform Pages</h3><div class="grc-export-check-grid">'+pageChecks+'</div></div><div id="grcSpecificRecords"></div>','Generate Excel','window._grcGenerateExcel()');setTimeout(refreshSpecificLists,0);
  };
  function simpleValue(v){if(v==null)return'';if(Array.isArray(v))return v.map(function(x){return typeof x==='object'?JSON.stringify(x):x;}).join('; ');if(typeof v==='object')return JSON.stringify(v);return v;}
  function rowsForPage(id,data,depts,specificPolicies,specificForms){
    var rows=[],source=[],columns=[];
    function filtered(key){return(data[key]||[]).filter(function(r){return deptMatch(r,depts);});}
    if(id==='executive')return{title:'Executive Command',columns:['Metric','Value'],rows:[['Policies',filtered('policies').length],['Plans',filtered('plans').length],['Forms',filtered('forms').length],['Risks',filtered('risks').length],['Incidents',filtered('incidents').length],['Action Plans',filtered('actions').length],['Documents',filtered('documents').length],['Reports',(data._reports||[]).length],['Manuals',(data.manuals||[]).length]]};
    if(id==='governance'){
      var p=filtered('policies').filter(function(r){return !specificPolicies.length||specificPolicies.indexOf(recordKey(r))>=0;});
      var pl=filtered('plans');var f=filtered('forms').filter(function(r){return !specificForms.length||specificForms.indexOf(recordKey(r))>=0;});
      columns=['Record Type','Code','Name','Department','Issue Date','Effective Date','Review Date','Status','Scope'];
      p.forEach(function(r){rows.push(['Policy',r.code||r.id,r.nameEn||r.name||r.title,r.department,r.issueDate,r.effectiveDate,r.reviewDate,r.status,'']);});
      pl.forEach(function(r){rows.push(['Plan',r.code||r.id,r.nameEn||r.name||r.title,r.department,r.issueDate,r.effectiveDate,r.reviewDate,r.status,'']);});
      f.forEach(function(r){rows.push(['Form',r.code||r.id,r.nameEn||r.name||r.title,r.department,r.issueDate,r.effectiveDate,r.reviewDate,r.status,r.scope]);});return{title:'Governance',columns:columns,rows:rows};
    }
    if(id==='risk'){columns=['Record Type','Code','Description','Department','Category','Likelihood','Impact','Score','Level','Status'];filtered('risks').forEach(function(r){rows.push(['Risk',r.id,r.riskIdentified,r.department,r.riskCategory,r.likelihood,r.impact,r.riskScore||Number(r.likelihood||0)*Number(r.impact||0),r.riskLevel,r.actionStatus]);});filtered('incidents').forEach(function(r){rows.push(['Incident',r.id,r.title||r.description,r.department,r.category,'','','','',r.status]);});filtered('codes').forEach(function(r){rows.push(['Emergency Code',r.id,r.name||r.title,r.department,r.type,'','','','',r.status]);});return{title:'Risk Management',columns:columns,rows:rows};}
    if(id==='register'){columns=['Register','Code','Name / Description','Department','Status'];['policies','plans','forms','risks','incidents','codes','actions','documents'].forEach(function(k){filtered(k).forEach(function(r){rows.push([k,r.code||r.id,r.nameEn||r.name||r.titleEn||r.title||r.riskIdentified||r.description,r.department,r.status||r.actionStatus]);});});return{title:'Registers',columns:columns,rows:rows};}
    if(id==='compliance'){source=filtered('compliance');columns=['Code','Authority','Requirement','Department','Status','Gap','CAP'];source.forEach(function(r){rows.push([r.code||r.id,r.authority||r.standard,r.requirement||r.description,r.department,r.status,r.gap||r.gapAnalysis,r.cap||r.correctiveAction]);});return{title:'Compliance',columns:columns,rows:rows};}
    if(id==='actions'){source=filtered('actions');columns=['Code','Action','Department','Source','Owner','Due Date','Status','Progress'];source.forEach(function(r){rows.push([r.code||r.id,r.name||r.title||r.action,r.department,r.source,r.owner,r.dueDate,r.status,r.progress]);});return{title:'Action Plans',columns:columns,rows:rows};}
    if(id==='documents'){source=filtered('documents');columns=['Code','Document','Department','Category','Version','Issue Date','Status'];source.forEach(function(r){rows.push([r.code||r.id,r.name||r.title,r.department,r.category,r.version,r.issueDate,r.status]);});return{title:'Documents & Records',columns:columns,rows:rows};}
    if(id==='reports'){source=data._reports||[];columns=['Code','Report Name','Family','Type','Year','Quarter','Status'];source.forEach(function(r){rows.push([r.code||r.id,r.titleEn||r.title||r.name,r.family,r.kind||r.type,r.year,r.quarter,r.status||'Available']);});return{title:'Reports',columns:columns,rows:rows};}
    if(id==='manuals'){source=data.manuals||[];columns=['Code','Manual / Guideline','Language','Version','Status'];source.forEach(function(r){rows.push([r.code||r.id,r.nameEn||r.name||r.title,r.language,r.version,r.status]);});return{title:'FMS Manual',columns:columns,rows:rows};}
    return{title:PAGE_LABELS[id]||id,columns:['Information'],rows:[['This page contains visual or interactive content. Use Report or Export for the formatted page view.']]};
  }
  function ensureExcelJs(){return new Promise(function(resolve,reject){if(window.ExcelJS)return resolve();var s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/exceljs@4.3.0/dist/exceljs.min.js';s.onload=resolve;s.onerror=function(){reject(new Error('Excel library could not be loaded.'));};document.head.appendChild(s);});}
  function logoBase64(){var im=document.querySelector('#grcApp .grc-logo img')||document.getElementById('logoImg');if(!im||!/^data:image/.test(im.src||''))return null;return im.src;}
  window._grcGenerateExcel=async function(){
    var pages=checked('grcExcelPage'),depts=checked('grcExcelDept'),specificPolicies=checked('grcSpecificPolicies'),specificForms=checked('grcSpecificForms');if(!pages.length){alert('Select at least one platform page.');return;}closeOverlay();
    try{await ensureExcelJs();var data=snap();try{if(typeof window._advisoryGetAll==='function')data._advisory=await window._advisoryGetAll();}catch(_){}
      var wb=new ExcelJS.Workbook();wb.creator='QUMC GRC Workspace';wb.created=new Date();var logo=logoBase64(),logoId=null;if(logo){try{logoId=wb.addImage({base64:logo,extension:logo.indexOf('png')>=0?'png':'jpeg'});}catch(_){}}
      pages.forEach(function(id){var set=rowsForPage(id,data,depts,specificPolicies,specificForms);if(id==='advisory'){var ar=(data._advisory||[]).filter(function(r){return String(r.platform||'grc')==='grc'&&(!depts.length||depts.indexOf(String(r.departmentKey||''))>=0);});set={title:'Advisory Center',columns:['Request Code','Request Type','Category','Related Records','Department','Gender','Priority','Status','Created','Rating'],rows:ar.map(function(r){return[r.code,r.requestTypeLabel,r.category,(r.relatedItems||[]).map(function(x){return(x.code?x.code+' — ':'')+x.name;}).join('; ')+(r.relatedNewText?'; New: '+r.relatedNewText:''),r.departmentKey,r.gender,r.priority,r.status,r.createdAtIso||'',r.rating||''];})};}
        var name=(set.title||PAGE_LABELS[id]||id).replace(/[\\\/?*\[\]:]/g,' ').slice(0,31),ws=wb.addWorksheet(name,{views:[{showGridLines:false,state:'frozen',ySplit:5}]});var cols=Math.max(2,set.columns.length);ws.mergeCells(1,1,1,cols);ws.getCell(1,1).value='QUMC — Governance, Risk & Compliance Report';ws.getCell(1,1).font={name:'Calibri',size:15,bold:true,color:{argb:'FFFFFFFF'}};ws.getCell(1,1).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF152538'}};ws.getCell(1,1).alignment={horizontal:'center',vertical:'middle'};ws.getRow(1).height=30;
        ws.mergeCells(2,1,2,cols);ws.getCell(2,1).value=set.title+' · Facility Management & Safety Division';ws.getCell(2,1).font={name:'Calibri',size:11,bold:true,color:{argb:'FF007A96'}};ws.getCell(2,1).alignment={horizontal:'center'};ws.mergeCells(3,1,3,cols);ws.getCell(3,1).value='Departments: '+(depts.length?depts.map(function(d){var x=DEPTS.find(function(z){return z[0]===d;});return x?x[1]:d;}).join(', '):'All')+' · Generated: '+new Date().toLocaleString('en-GB');ws.getCell(3,1).font={name:'Calibri',size:9,color:{argb:'FF64748B'}};ws.getCell(3,1).alignment={horizontal:'center'};
        if(logoId!=null)ws.addImage(logoId,{tl:{col:.15,row:.1},ext:{width:88,height:48}});ws.addRow([]);var hr=ws.addRow(set.columns);hr.height=26;hr.eachCell(function(c){c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF00A3C4'}};c.font={name:'Calibri',size:10,bold:true,color:{argb:'FFFFFFFF'}};c.alignment={horizontal:'center',vertical:'middle',wrapText:true};c.border={top:{style:'thin',color:{argb:'FFD6E2EE'}},bottom:{style:'thin',color:{argb:'FFD6E2EE'}},left:{style:'thin',color:{argb:'FFD6E2EE'}},right:{style:'thin',color:{argb:'FFD6E2EE'}}};});
        (set.rows.length?set.rows:[['No matching records']]).forEach(function(a,i){var r=ws.addRow(a.map(simpleValue));r.eachCell(function(c){c.font={name:'Calibri',size:9,color:{argb:'FF243B53'}};c.alignment={vertical:'middle',wrapText:true};c.fill={type:'pattern',pattern:'solid',fgColor:{argb:i%2?'FFF8FAFC':'FFFFFFFF'}};c.border={bottom:{style:'hair',color:{argb:'FFE2E8F0'}}};});});ws.columns.forEach(function(c,i){var max=12;[set.columns].concat(set.rows.slice(0,100)).forEach(function(a){max=Math.max(max,String(a[i]||'').length+2);});c.width=Math.min(42,max);});ws.autoFilter={from:{row:5,column:1},to:{row:5,column:set.columns.length}};
      });
      var buf=await wb.xlsx.writeBuffer(),blob=new Blob([buf],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='QUMC_GRC_Export_'+new Date().toISOString().slice(0,10)+'.xlsx';document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},1200);if(typeof window.addAudit==='function')window.addAudit('GRC_EXPORT_EXCEL','Exported GRC Excel: '+pages.join(', '));
    }catch(e){alert(String(e&&e.message||e));}
  };
  function parsePage(id){var live=document.querySelector('#grc-page-'+id);if(live)return live.cloneNode(true);var tmp=document.createElement('div');tmp.innerHTML=typeof window._grcGetPageHtml==='function'?window._grcGetPageHtml(id):'';return tmp;}
  window._grcOpenReportSelector=function(){var page=parsePage('executive'),sections=Array.prototype.slice.call(page.querySelectorAll('.grc-section'));var opts=sections.map(function(sec,i){var title=(sec.querySelector('.grc-section-title')||{}).textContent||('Section '+(i+1));return'<label class="grc-export-check"><input type="checkbox" name="grcReportSection" value="'+i+'" checked><span>'+esc((i+1)+'. '+title.trim())+'</span></label>';}).join('');overlay('GRC Executive Command Report','Select the Executive Command sections to include in the formatted PDF report.','<div class="grc-export-section"><h3>Report Sections</h3><div class="grc-export-check-grid">'+opts+'</div></div>','Build Report','window._grcGenerateReport()');};
  function printHost(title,subtitle,content){var old=document.getElementById('grcPrintHost');if(old)old.remove();var host=document.createElement('div');host.id='grcPrintHost';var logo=(document.querySelector('#grcApp .grc-logo img')||{}).src||'';host.innerHTML='<div class="grc-print-header">'+(logo?'<img src="'+esc(logo)+'" alt="QUMC">':'')+'<div><h1>'+esc(title)+'</h1><p>'+esc(subtitle)+'</p></div></div><div class="grc-print-meta">Generated: '+new Date().toLocaleString('en-GB')+' · Qassim University Medical City · Facility Management & Safety Division</div><div class="grc-print-body">'+content+'</div>';document.body.appendChild(host);document.body.classList.add('grc-printing');setTimeout(function(){var nativePrint=window.__qumcNativePrint||window.print;nativePrint.call(window);setTimeout(function(){document.body.classList.remove('grc-printing');host.remove();},600);},120);}
  window._grcGenerateReport=function(){var chosen=checked('grcReportSection').map(Number),page=parsePage('executive'),sections=Array.prototype.slice.call(page.querySelectorAll('.grc-section')),html='';chosen.forEach(function(i,n){var sec=sections[i];if(!sec)return;var c=sec.cloneNode(true),title=c.querySelector('.grc-section-title');if(title)title.innerHTML='<span class="grc-print-number">'+(n+1)+'</span>'+title.innerHTML;html+='<div class="grc-print-section">'+c.outerHTML+'</div>';});if(!html){alert('Select at least one report section.');return;}closeOverlay();printHost('GRC Executive Command Report','Selected executive indicators, charts and results',html);if(typeof window.addAudit==='function')window.addAudit('GRC_REPORT_PDF','Generated Executive Command report');};
  window._grcToggleExportMenu=function(e){if(e)e.stopPropagation();var m=document.getElementById('grcExportMenu');if(m)m.classList.toggle('is-open');};
  document.addEventListener('click',function(e){var m=document.getElementById('grcExportMenu');if(m&&!e.target.closest('.grc-export-menu-wrap'))m.classList.remove('is-open');});
  window._grcExportPage=function(id){var menu=document.getElementById('grcExportMenu');if(menu)menu.classList.remove('is-open');var mods=modules(),ids=id==='all'?mods.map(function(x){return x.id;}):[id],html='';ids.forEach(function(pid,n){var page=parsePage(pid),label=PAGE_LABELS[pid]||(mods.find(function(x){return x.id===pid;})||{}).label||pid;if(n)html+='<div style="page-break-before:always"></div>';html+='<section class="grc-print-section"><h2 style="font-size:16px;color:#152538;border-bottom:3px solid #00A3C4;padding-bottom:7px"><span class="grc-print-number">'+(n+1)+'</span>'+esc(label)+'</h2>'+page.innerHTML+'</section>';});printHost(id==='all'?'GRC Workspace — All Pages':(PAGE_LABELS[id]||id),'Formatted page export',html);if(typeof window.addAudit==='function')window.addAudit('GRC_PAGE_EXPORT','Exported GRC page: '+id);};
})();
