/* QUMC GRC1 Workspace Chat — isolated from Performance and GRC chat */
(function(){
  'use strict'; if(window.__QUMC_GRC1_CHAT_V177__)return; window.__QUMC_GRC1_CHAT_V177__=true;
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function snap(){try{return typeof window._grc1GetExportSnapshot==='function'?(window._grc1GetExportSnapshot()||{}):{};}catch(_){return{};}}
  function counts(){var s=snap();return{policies:(s.policies||[]).length,forms:(s.forms||[]).length,plans:(s.plans||[]).length,risks:(s.risks||[]).length,incidents:(s.incidents||[]).length,codes:(s.codes||[]).length,actions:(s.actions||[]).length,initiatives:(s.initiatives||[]).length,cbahi:(s._cbahiAssessment||[]).length,jci:(s._jciAssessment||[]).length};}
  function answer(q){var c=counts(),t=String(q||'').toLowerCase();
    if(/risk|مخاطر/.test(t))return 'Risk Management currently contains '+c.risks+' risks, '+c.incidents+' incidents and '+c.codes+' emergency-code records. Open Risk Management for levels, heat map and department details.';
    if(/compliance|cbahi|jci|امتثال|سباهي/.test(t))return 'Compliance contains '+c.cbahi+' CBAHI assessment rows and '+c.jci+' JCI assessment rows. Use the Compliance page to review status, evidence and gaps.';
    if(/governance|policy|form|plan|حوكمة|سياس/.test(t))return 'Governance currently contains '+c.policies+' policies, '+c.forms+' forms and '+c.plans+' plans. Use Governance or Registers to filter by department and status.';
    if(/initiative|مباد/.test(t))return 'There are '+c.initiatives+' initiatives in the current GRC1 workspace.';
    return 'GRC1 snapshot: '+c.policies+' policies, '+c.forms+' forms, '+c.plans+' plans, '+c.risks+' risks, '+c.incidents+' incidents and '+c.actions+' action-plan records. Ask about Governance, Risk Management, Compliance or Initiatives.';
  }
  function add(text,who){var box=document.getElementById('grc1AiMsgs');if(!box)return;var d=document.createElement('div');d.className='ai-msg-bubble '+(who==='user'?'user':'assistant');d.innerHTML=esc(text);box.appendChild(d);box.scrollTop=box.scrollHeight;}
  window._grc1AiToggle=function(force){window._grc1ChatEnsure&&window._grc1ChatEnsure();var w=document.getElementById('grc1AiWin');if(!w)return;var visible=w.classList.contains('open')||w.style.display==='flex';var show=typeof force==='boolean'?force:!visible;w.classList.toggle('open',show);w.style.display=show?'flex':'none';w.setAttribute('aria-hidden',show?'false':'true');if(show){var i=document.getElementById('grc1AiInp');if(i)setTimeout(function(){i.focus();},30);}};
  window._grc1AiSend=function(){var i=document.getElementById('grc1AiInp'),q=String(i&&i.value||'').trim();if(!q)return;add(q,'user');i.value='';setTimeout(function(){add(answer(q),'bot');},120);};
  window._grc1AiSuggest=function(q){var i=document.getElementById('grc1AiInp');if(i)i.value=q;window._grc1AiSend();};
  window._grc1ChatEnsure=function(){var existing=document.getElementById('grc1AiFloatBtn');if(existing){var inGrc=document.body.classList.contains('grc-mode')&&String(window.__qumcActivePortal||'').toLowerCase()==='grc1';existing.style.display=inGrc?'grid':'none';var w=document.getElementById('grc1AiWin');if(w&&!inGrc){w.classList.remove('open');w.style.display='none';w.setAttribute('aria-hidden','true');}return;}var btn=document.createElement('button');btn.id='grc1AiFloatBtn';btn.className='ai-float-btn grc-ai-float';btn.type='button';btn.title='GRC1 Chat';btn.innerHTML='<span class="ai-float-chart">💬</span>';btn.onclick=window._grc1AiToggle;var win=document.createElement('section');win.id='grc1AiWin';win.className='ai-chat-window grc-ai-window';win.style.display='none';win.setAttribute('aria-hidden','true');win.innerHTML='<div class="ai-chat-head"><div class="ai-chat-title-wrap"><div class="ai-chat-icon">💬</div><div><div class="ai-chat-title">GRC1 Chat</div><div class="ai-chat-subtitle">Workspace insights</div></div></div><button type="button" class="ai-chat-close" onclick="window._grc1AiToggle()" aria-label="Close chat"></button></div><div class="ai-chat-messages" id="grc1AiMsgs"><div class="ai-msg-bubble assistant"><b>Hi 👋</b><br>Ask about Governance, Risk Management, Compliance or Initiatives.</div><div class="ai-suggestion-row"><button onclick="window._grc1AiSuggest(\'Summarize GRC1\')">Summary</button><button onclick="window._grc1AiSuggest(\'Show risk overview\')">Risks</button><button onclick="window._grc1AiSuggest(\'Show compliance overview\')">Compliance</button></div></div><div class="ai-chat-inputbar"><textarea id="grc1AiInp" rows="1" placeholder="Ask about GRC1…"></textarea><button id="grc1AiSendBtn" onclick="window._grc1AiSend()" aria-label="Send message">➤</button></div>';document.body.appendChild(btn);document.body.appendChild(win);btn.style.display=(document.body.classList.contains('grc-mode')&&String(window.__qumcActivePortal||'').toLowerCase()==='grc1')?'grid':'none';var inp=win.querySelector('#grc1AiInp');inp.addEventListener('keydown',function(e){if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();window._grc1AiSend();}});};
  document.addEventListener('DOMContentLoaded',window._grc1ChatEnsure);setInterval(window._grc1ChatEnsure,1200);
})();
